<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Reference distributions</title>

<script src="site_libs/header-attrs-2.5/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="SI-md-08.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Geographic Data Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="overview.html">Overview</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lecture topics</li>
    <li>
      <a href="lec01.html">Introduction to the course</a>
    </li>
    <li>
      <a href="lec02.html">Univariate plots</a>
    </li>
    <li>
      <a href="lec03.html">Bivariate plots</a>
    </li>
    <li>
      <a href="lec04.html">Descriptive statistics</a>
    </li>
    <li>
      <a href="lec05.html">Multivariate plots</a>
    </li>
    <li>
      <a href="ggplot2.html">ggplot2 versions of basic plots</a>
    </li>
    <li>
      <a href="lec06.html">Maps in R</a>
    </li>
    <li>
      <a href="lec07.html">Geospatial analysis in R</a>
    </li>
    <li>
      <a href="lec08.html">Data wrangling and matrix algebra</a>
    </li>
    <li>
      <a href="lec09.html">Reference distributions</a>
    </li>
    <li>
      <a href="lec10.html">Statistical inference</a>
    </li>
    <li>
      <a href="lec11.html">Analysis of variance</a>
    </li>
    <li>
      <a href="lec12.html">Regression analysis</a>
    </li>
    <li>
      <a href="lec13.html">More regression analysis</a>
    </li>
    <li>
      <a href="lec14.html">Nonparametric regression</a>
    </li>
    <li>
      <a href="lec15.html">GLMs, GAMs, and CARTs</a>
    </li>
    <li>
      <a href="lec16.html">Principal components and factor analyses</a>
    </li>
    <li>
      <a href="lec17.html">MANOVA and discriminant analysis</a>
    </li>
    <li>
      <a href="lec18.html">Multivariate distances and cluster analysis</a>
    </li>
    <li>
      <a href="lec19.html">High-resolution and high-dimension data</a>
    </li>
    <li>
      <a href="lec20.html">Analysis and visualization of large raster data sets</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Exercises</li>
    <li>
      <a href="ex01.html">Exercise 01 -- Getting R and RStudio</a>
    </li>
    <li>
      <a href="ex02.html">Exercise 02 -- Univariate plots</a>
    </li>
    <li>
      <a href="ex03.html">Exercise 03 -- Bivariate plots and descriptive statistics</a>
    </li>
    <li>
      <a href="ex04.html">Exercise 04 -- Multivariate plots</a>
    </li>
    <li>
      <a href="ex05.html">Exercise 05 -- Data wrangling and matrix algebra</a>
    </li>
    <li>
      <a href="ex06.html">Exercise 06 -- CI's, t-tests, ANOVA</a>
    </li>
    <li>
      <a href="ex07.html">Exercise 07 -- Regression analysis</a>
    </li>
    <li>
      <a href="ex08.html">Exercise 08 -- Multivariate analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="packages-and-data.html">Packages and data</a>
    </li>
    <li>
      <a href="vm_inst.html">Virtual machine instructions</a>
    </li>
    <li>
      <a href="readings.html">Readings</a>
    </li>
    <li>
      <a href="datasets.html">Datasets</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reference distributions</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction-significance-evaluation"><span class="toc-section-number">1</span> Introduction – Significance evaluation</a></li>
<li><a href="#empirical-reference-distributions"><span class="toc-section-number">2</span> Empirical reference distributions</a>
<ul>
<li><a href="#use-of-an-empirical-reference-distribution"><span class="toc-section-number">2.1</span> Use of an empirical reference distribution</a>
<ul>
<li><a href="#how-unusual-is-a-particular-observation-of-tsum"><span class="toc-section-number">2.1.1</span> How unusual is a particular observation of <code>TSum</code>?</a></li>
<li><a href="#what-value-of-tsum-is-exceeded-10-percent-of-the-time"><span class="toc-section-number">2.1.2</span> What value of <code>TSum</code> is exceeded 10 percent of the time?</a></li>
<li><a href="#how-unusual-is-the-mean-of-the-last-30-years-of-the-record"><span class="toc-section-number">2.1.3</span> How unusual is the mean of the last 30 years of the record?</a></li>
</ul></li>
</ul></li>
<li><a href="#a-theoretical-reference-distribution-the-normal-or-standard-normal-distribution"><span class="toc-section-number">3</span> A theoretical reference distribution – the normal (or standard normal) distribution</a>
<ul>
<li><a href="#density-functions-for-the-normal-distribution"><span class="toc-section-number">3.1</span> Density functions for the normal distribution</a></li>
<li><a href="#the-central-limit-theorem"><span class="toc-section-number">3.2</span> The Central Limit Theorem</a>
<ul>
<li><a href="#empirical-demonstration-of-the-central-limit-theorem"><span class="toc-section-number">3.2.1</span> Empirical demonstration of the Central Limit Theorem</a></li>
</ul></li>
<li><a href="#other-theoretical-reference-distributions"><span class="toc-section-number">3.3</span> Other theoretical reference distributions</a></li>
</ul></li>
<li><a href="#readings"><span class="toc-section-number">4</span> Readings</a></li>
</ul>
</div>

<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>
<span style="color: #00cc00;">NOTE: This page has been revised for Winter 2021, but may undergo further edits.</span>
</p>
<div id="introduction-significance-evaluation" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction – Significance evaluation</h1>
<p>Descriptive statistics (like the mean or standard deviation) are useful for characterizing a set of observations, but the significance of a particular value of a statistic (i.e. is it large or small? commonplace or unusual?) will in general not be immediately apparent, and must be judged using some external (to the data set) standard.</p>
<p>The significance of a particular value of a statistic (e.g. the 30-yr mean annual temperature of a place) can be evaluated by determining how rare or how commonplace that particular value is. In ordinary practice, those values of a statistic with absolute values that are equaled or exceeded in no more than 5% of the realizations of that statistic are regarded as significant.</p>
<p>The significance of a particular value of a statistic can be judged by comparing that value to the distribution of “all” values of the statistic. That distribution is known as the reference distribution, and in practice, can be either an <em>empirical distribution</em> (as represented by a histogram or cumulative frequency curve for an actual data set), or a <em>theoretical distribution</em> (as represented by an equation or function).</p>
</div>
<div id="empirical-reference-distributions" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Empirical reference distributions</h1>
<p>Empirical reference distributions are contructed using observed (i.e. real) data sets, which if sufficently large, allow statements to be made about the chances of observing particular values of a variable–possibly new obervations of the variable, or of observing combinations of values of a variable, such as the mean for some subset of observations.</p>
<p>If a relatively large data set exists, then the distribution of a particular statistic (e.g. a 30-yr mean) can be created by repeatedly</p>
<ul>
<li>drawing a sample from the data set,</li>
<li>calculating the value of the statistic for the sample,</li>
<li>saving the statistic, and then</li>
</ul>
<p>and, after a sufficient number of samples have been taken (the more the better),</p>
<ul>
<li>looking at the distribution of the sample statistics (via the histogram or other plot, or by direct inspection).</li>
</ul>
<div id="use-of-an-empirical-reference-distribution" class="section level2" number="2.1">
<h2 number="2.1"><span class="header-section-number">2.1</span> Use of an empirical reference distribution</h2>
<p>The examples here use the 1189-year-long time series of summer temperature (TSum) for the Sierra Nevada, as reconstructed from tree-ring data (Graumlich, 1993). [<code>sierra.csv</code>] This data set is sufficiently long enough to illustrate the idea of having a large amount of empirical information to base judgements about the <em>significance</em> (or the relative unusualness) of individual values or statistics.</p>
<div id="how-unusual-is-a-particular-observation-of-tsum" class="section level3" number="2.1.1">
<h3 number="2.1.1"><span class="header-section-number">2.1.1</span> How unusual is a particular observation of <code>TSum</code>?</h3>
<p>To answer this question, the appropriate reference distribution is the one formed by all of the individual observations of <code>TSum</code>. In other words, the entire data set should be used to answer questions about the significance (or relative size) of an individual observation, simply by comparing that observation to all other observations. This comparison is facilitated by first sorting the observations, and then creating a new variable that indicates the relative position within the sorted observations of each observation.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sierra Nevada tree-ring summer temperature reconstructions</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(sierra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># sort and rank TSum values</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sort_Tsum <span class="ot">&lt;-</span> <span class="fu">sort</span>(TSum) <span class="co"># arranges values from low to high</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>rank_Tsum <span class="ot">&lt;-</span> <span class="fu">rank</span>(TSum) <span class="co"># replaces values with rank number (1 to n)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the sorted and ranked values</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># close window to exit</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>sierra_sort <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Year, TSum, <span class="fu">rank</span>(TSum), sort_Tsum, <span class="fu">rank</span>(sort_Tsum),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>     Year[<span class="fu">rank</span>(TSum)])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sierra_sort)</span></code></pre></div>
<pre><code>##   Year  TSum rank.TSum. sort_Tsum rank.sort_Tsum. Year.rank.TSum..
## 1  800 15.68      667.0     13.68             1.0             1466
## 2  801 14.00       58.0     13.70             2.0              857
## 3  802 15.41      579.5     13.71             3.0             1378
## 4  803 15.28      523.5     13.74             4.5             1322
## 5  804 16.14      849.5     13.74             4.5             1648
## 6  805 16.99     1093.5     13.75             6.0             1892</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(sierra_sort)</span></code></pre></div>
<pre><code>##      Year  TSum rank.TSum. sort_Tsum rank.sort_Tsum. Year.rank.TSum..
## 1184 1983 16.79     1047.0     17.38          1182.5             1846
## 1185 1984 16.71     1018.0     17.39          1185.5             1817
## 1186 1985 16.68     1010.5     17.39          1185.5             1809
## 1187 1986 17.33     1169.0     17.41          1187.0             1968
## 1188 1987 14.26      149.5     17.45          1188.0              948
## 1189 1988 14.99      395.0     17.48          1189.0             1194</code></pre>
<p>The table can be inspected by opening it in a data viewer:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(sierra_sort)</span></code></pre></div>
<p>From this table, for example, the value 13.79 C can be seen to have occurred three times, in 1101, 1479, and 1892, and is a relatively low value of temperature, in contrast to the highest temperature value, 17.48, which occurred in 1194.</p>
<p>Similar information can be gained from the histogram.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nice histogram</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>cutpts <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">12.0</span>, <span class="fl">18.0</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(TSum, <span class="at">breaks=</span>cutpts, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">13</span>,<span class="dv">18</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(TSum))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(TSum)</span></code></pre></div>
<p><img src="lec09_files/figure-html/refDist02-1.png" width="2100" /></p>
</div>
<div id="what-value-of-tsum-is-exceeded-10-percent-of-the-time" class="section level3" number="2.1.2">
<h3 number="2.1.2"><span class="header-section-number">2.1.2</span> What value of <code>TSum</code> is exceeded 10 percent of the time?</h3>
<p>Other information can be gained by examining the empirical cumulative density function, which is a plot of the sorted values of <code>TSum</code> and the probability of equaling or exceeding that value in the data set</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># empirical cumulative density function</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ecdf_Tsum <span class="ot">&lt;-</span> <span class="fu">rank</span>(sort_Tsum)<span class="sc">/</span><span class="fu">length</span>(TSum)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sort_Tsum, ecdf_Tsum, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="lec09_files/figure-html/refDist03-1.png" width="2100" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sierra_ecdf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Year, TSum, <span class="fu">rank</span>(TSum), sort_Tsum, <span class="fu">rank</span>(sort_Tsum),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>     Year[<span class="fu">rank</span>(TSum)], ecdf_Tsum)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sierra_ecdf); <span class="fu">tail</span>(sierra_ecdf)</span></code></pre></div>
<pre><code>##   Year  TSum rank.TSum. sort_Tsum rank.sort_Tsum. Year.rank.TSum..    ecdf_Tsum
## 1  800 15.68      667.0     13.68             1.0             1466 0.0008410429
## 2  801 14.00       58.0     13.70             2.0              857 0.0016820858
## 3  802 15.41      579.5     13.71             3.0             1378 0.0025231287
## 4  803 15.28      523.5     13.74             4.5             1322 0.0037846930
## 5  804 16.14      849.5     13.74             4.5             1648 0.0037846930
## 6  805 16.99     1093.5     13.75             6.0             1892 0.0050462574</code></pre>
<pre><code>##      Year  TSum rank.TSum. sort_Tsum rank.sort_Tsum. Year.rank.TSum.. ecdf_Tsum
## 1184 1983 16.79     1047.0     17.38          1182.5             1846 0.9945332
## 1185 1984 16.71     1018.0     17.39          1185.5             1817 0.9970563
## 1186 1985 16.68     1010.5     17.39          1185.5             1809 0.9970563
## 1187 1986 17.33     1169.0     17.41          1187.0             1968 0.9983179
## 1188 1987 14.26      149.5     17.45          1188.0              948 0.9991590
## 1189 1988 14.99      395.0     17.48          1189.0             1194 1.0000000</code></pre>
<p>Again, the specific answer can be obtained by inspection of the data sheet, the histogram, or the Line plot of ProbTSum vs SortTSum.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(sierra_ecdf)</span></code></pre></div>
<p>Alternatively, the values corresponding to specific quantiles can be gotten by the following command:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(TSum, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.0</span>,.<span class="dv">05</span>,.<span class="dv">10</span>,.<span class="dv">25</span>,.<span class="dv">50</span>,.<span class="dv">75</span>,.<span class="dv">90</span>,.<span class="dv">95</span>, <span class="fl">1.0</span>))</span></code></pre></div>
<pre><code>##     0%     5%    10%    25%    50%    75%    90%    95%   100% 
## 13.680 14.014 14.180 14.730 15.450 16.290 16.870 17.160 17.480</code></pre>
</div>
<div id="how-unusual-is-the-mean-of-the-last-30-years-of-the-record" class="section level3" number="2.1.3">
<h3 number="2.1.3"><span class="header-section-number">2.1.3</span> How unusual is the mean of the last 30 years of the record?</h3>
<p>The following command gets the mean of the last 30 yrs of data:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(TSum[(<span class="fu">length</span>(TSum)<span class="sc">-</span><span class="dv">29</span>)<span class="sc">:</span>(<span class="fu">length</span>(TSum))])</span></code></pre></div>
<pre><code>## [1] 15.848</code></pre>
<p>To answer the above question, the appropriate reference distribution is no longer that formed from the whole data set, but instead is the distribution that would be formed by a set of mean values of 30-year long samples from the data. This set can be obtained by repeated sampling of the <code>TSum</code> data using the following:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># repeated sampling and calculation of means</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># number of samples</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>Means30yr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsamp) {</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>     samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(TSum, <span class="dv">30</span>, <span class="at">replace=</span>T)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>          Means30yr[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>     }</span></code></pre></div>
<p>The script causes causes <code>nsamp</code> samples of 30 observations each to be drawn at random from the column of data containing <code>TSum</code>. For each sample, the mean is calculated, and stored in the variable <code>Means30yr</code>. The distribution of this variable (<code>Means30yr</code>) rather than that of the original data is the appropriate one for answering the above question.</p>
<p>The two empirical reference distributions can be compared by looking at their histograms:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histograms of data and of 30-Means</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>cutpts <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">12.0</span>, <span class="fl">18.0</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(TSum, <span class="at">breaks=</span>cutpts, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">20</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(TSum))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Means30yr, <span class="at">breaks=</span>cutpts, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">20</span>))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(Means30yr))</span></code></pre></div>
<p><img src="lec09_files/figure-html/refDist07-1.png" width="2100" /></p>
<p>The above procedure draws 30 years at random from TSum. It might be more appropriate to draw 30-consecutive-year samples from TSum. This can be done as follows:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># repeated sampling and calculation of means</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># consecutive samples</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># number of samples</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>Means30yrb <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsamp) {</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>     start <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="at">min=</span><span class="dv">1</span>, <span class="at">max=</span><span class="fu">length</span>(Year)<span class="sc">-</span><span class="dv">30</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>     start <span class="ot">&lt;-</span> <span class="fu">round</span>(start)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>     sampmean <span class="ot">&lt;-</span> <span class="fl">0.0</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>     <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>) {</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>          sampmean <span class="ot">&lt;-</span> sampmean <span class="sc">+</span> TSum[start<span class="sc">+</span>j<span class="dv">-1</span>]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>     }</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>     Means30yrb[i] <span class="ot">&lt;-</span> sampmean<span class="sc">/</span><span class="fl">30.0</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>And here are the histograms:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histograms of data and of 30-Means from consecutive samples</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>cutpts <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">12.0</span>, <span class="fl">18.0</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(TSum, <span class="at">breaks=</span>cutpts, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">20</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(TSum))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Means30yrb, <span class="at">breaks=</span>cutpts, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">20</span>))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(Means30yrb))</span></code></pre></div>
<p><img src="lec09_files/figure-html/refDist09-1.png" width="2100" /></p>
<p>Note that this approach for using an empirical reference distribution is a general one–the significance of other statistics (e.g. the variance) can be evaluated the same way.</p>
<p><a href="lec09.html">[Back to top]</a></p>
</div>
</div>
</div>
<div id="a-theoretical-reference-distribution-the-normal-or-standard-normal-distribution" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> A theoretical reference distribution – the normal (or standard normal) distribution</h1>
<p>Much of the time, a data set large enough to make probabilistic-type statements about the values of a statistic does not exist, or the statistic may be difficult to observe. In such cases, theoretical reference distributions allow the significance of particular values of statistics to be evaluated. One distribution that is applicable to many cases in practice is the normal distribution, and the Central Limit Theorem explains the source of that general applicability.</p>
<ul>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/topics/normaldist.pdf">the normal distribution</a></li>
</ul>
<div id="density-functions-for-the-normal-distribution" class="section level2" number="3.1">
<h2 number="3.1"><span class="header-section-number">3.1</span> Density functions for the normal distribution</h2>
<p>The standard normal distribution is widely used in inferential statistics, owing to its:</p>
<ul>
<li>applicability (many processes are intrinsically normally distributed, and the central limit theorem assures us that sample means, in specific, and many processes that involve summation or integration, in general, are normally distributed)</li>
<li>simplicity (it has a relatively simple shape, owing to the particular choice of values for its two parameters, mu and sigma)</li>
</ul>
<p>The standard normal distribution is described by an equation and is represented by its:</p>
<p>Probability density function (pdf) (R/S-Plus term is Density),</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability density function</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">+</span><span class="dv">3</span>, <span class="at">by=</span>.<span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>pdf_norm<span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, pdf_norm, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="lec09_files/figure-html/normal01-1.png" width="2100" /></p>
<p>Cumulative density function (cdf) (R/S-Plus term is Probability), and</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cumulative density function</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="sc">+</span><span class="dv">3</span>, <span class="at">by=</span>.<span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>cdf_norm<span class="ot">&lt;-</span><span class="fu">pnorm</span>(x, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, cdf_norm, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="lec09_files/figure-html/normal02-1.png" width="2100" /></p>
<p>Inverse cumulative density function (invcdf) (R/S-Plus term is Quantile).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inverse cumulative density function</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>invcdf_norm<span class="ot">&lt;-</span> <span class="fu">qnorm</span>(pr, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pr, invcdf_norm, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="lec09_files/figure-html/normal03-1.png" width="2100" /></p>
<p>Random numbers drawn from the normal distribution can be obtained as follows</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># normally distributed random numbers</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">1000</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(z, <span class="at">nclass=</span><span class="dv">40</span>)</span></code></pre></div>
<p><img src="lec09_files/figure-html/normal04-1.png" width="2100" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(z)</span></code></pre></div>
<p><img src="lec09_files/figure-html/normal04-2.png" width="2100" /></p>
</div>
<div id="the-central-limit-theorem" class="section level2" number="3.2">
<h2 number="3.2"><span class="header-section-number">3.2</span> The Central Limit Theorem</h2>
<p>The Central Limit Theorem provides the explanation for the wide applicability of the normal distribution in significance testing, because it guarantees us that (providing certain assumptions are met) that statistics (like the mean) obtained by integrating (as in summing up for computing the mean) will turn out to be normally distributed, no matter what the distribution of the underlying data is.</p>
<p>The Central Limit Theorem is a mathematical demonstration that statistics (like the mean) that are based on summations or integrations of a set of observations are normally distributed, no matter what the distribution is of the data from which samples are being drawn. The theorem therefore assures us that the normal distribution is the appropriate reference distribution for a sample mean to be compared with, in order to judge the relative size of that sample mean_</p>
<div id="empirical-demonstration-of-the-central-limit-theorem" class="section level3" number="3.2.1">
<h3 number="3.2.1"><span class="header-section-number">3.2.1</span> Empirical demonstration of the Central Limit Theorem</h3>
<p>Generate 1000 random numbers from four different distributions, the standard normal, the normal, the log-normal and uniform distributions. Histograms of the random numbers will make it clear what the shape of the distributions are like</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>stdNormal <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>Normal <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean=</span><span class="fl">4.0</span>, <span class="at">sd=</span><span class="fl">2.0</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>logNormal <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(n, <span class="at">meanlog=</span><span class="fl">1.0</span>, <span class="at">sdlog=</span><span class="fl">0.5</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>Uniform <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min=</span><span class="fl">0.0</span>, <span class="at">max=</span><span class="fl">1.0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(stdNormal)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Normal)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(logNormal)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Uniform)</span></code></pre></div>
<p><img src="lec09_files/figure-html/central02-1.png" width="2100" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>par <span class="ot">&lt;-</span> opar</span></code></pre></div>
<p>The following script generates nsamp sample means from one of these distributions</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take repeated samples from each distribution and calculate and save means</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># repeated sampling and calculation of means</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>nsamp <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># number of samples</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>mean_stdNormal <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>mean_normal <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>mean_logNormal <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>mean_Uniform <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span>nsamp) <span class="co"># matrix to hold means</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsamp) {</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>     samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(stdNormal, <span class="dv">30</span>, <span class="at">replace=</span>T)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>     mean_stdNormal[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>     samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(Normal, <span class="dv">30</span>, <span class="at">replace=</span>T)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>     mean_normal[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>     samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(logNormal, <span class="dv">30</span>, <span class="at">replace=</span>T)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>     mean_logNormal[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>     samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(Uniform, <span class="dv">30</span>, <span class="at">replace=</span>T)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>     mean_Uniform[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Histograms of the original data, as well as of the sample means can be obtained with the following script.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histograms of data and of sample means</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># standard Normal</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>xmax <span class="ot">&lt;-</span> <span class="fu">max</span>(stdNormal)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>xmin <span class="ot">&lt;-</span> <span class="fu">min</span>(stdNormal)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(stdNormal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mean_stdNormal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span></code></pre></div>
<p><img src="lec09_files/figure-html/central04-1.png" width="2100" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normal</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>xmax <span class="ot">&lt;-</span> <span class="fu">max</span>(Normal)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>xmin <span class="ot">&lt;-</span> <span class="fu">min</span>(Normal)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Normal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mean_normal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span></code></pre></div>
<p><img src="lec09_files/figure-html/central04-2.png" width="2100" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log Normal</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>xmax <span class="ot">&lt;-</span> <span class="fu">max</span>(logNormal)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>xmin <span class="ot">&lt;-</span> <span class="fu">min</span>(logNormal)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(logNormal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mean_logNormal, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span></code></pre></div>
<p><img src="lec09_files/figure-html/central04-3.png" width="2100" /></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Uniform</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>xmax <span class="ot">&lt;-</span> <span class="fu">max</span>(Uniform)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>xmin <span class="ot">&lt;-</span> <span class="fu">min</span>(Uniform)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Uniform, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mean_Uniform, <span class="at">nclass=</span><span class="dv">40</span>, <span class="at">probability=</span>T, <span class="at">xlim=</span><span class="fu">c</span>(xmin,xmax))</span></code></pre></div>
<p><img src="lec09_files/figure-html/central04-4.png" width="2100" /></p>
<p><a href="lec09.html">[Back to top]</a></p>
</div>
</div>
<div id="other-theoretical-reference-distributions" class="section level2" number="3.3">
<h2 number="3.3"><span class="header-section-number">3.3</span> Other theoretical reference distributions</h2>
<p>Although the normal distribution is applicable in a number of situations (owing to the implications of the Central Limit Theorem), other situations arise, in which other referernce distributions may apply.</p>
<ul>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/topics/theoretical.pdf">details of other reference distributions</a></li>
</ul>
<p><a href="lec09.html">[Back to top]</a></p>
</div>
</div>
<div id="readings" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Readings</h1>
<ul>
<li>Owen (The R Guide): Ch. 6</li>
<li>Irizarry (<em>Intro to Data Science</em>): Ch. 12 - 15</li>
</ul>
<p><a href="lec09.html">[Back to top]</a></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
