<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>More regression analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="SI-md-08.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Geographic Data Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="overview.html">Overview</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lecture topics</li>
    <li>
      <a href="lec01.html">Introduction to the course</a>
    </li>
    <li>
      <a href="lec02.html">Univariate plots</a>
    </li>
    <li>
      <a href="lec03.html">Bivariate plots</a>
    </li>
    <li>
      <a href="lec04.html">Descriptive statistics</a>
    </li>
    <li>
      <a href="lec05.html">Multivariate plots</a>
    </li>
    <li>
      <a href="ggplot2.html">ggplot2 versions of basic plots</a>
    </li>
    <li>
      <a href="lec06.html">Maps in R</a>
    </li>
    <li>
      <a href="lec07.html">Geospatial analysis in R</a>
    </li>
    <li>
      <a href="lec08.html">Data wrangling and matrix algebra</a>
    </li>
    <li>
      <a href="lec09.html">Reference distributions</a>
    </li>
    <li>
      <a href="lec10.html">Statistical inference</a>
    </li>
    <li>
      <a href="lec11.html">Analysis of variance</a>
    </li>
    <li>
      <a href="lec12.html">Regression analysis</a>
    </li>
    <li>
      <a href="lec13.html">More regression analysis</a>
    </li>
    <li>
      <a href="lec14.html">Nonparametric regression</a>
    </li>
    <li>
      <a href="lec15.html">GLMs, GAMs, and CARTs</a>
    </li>
    <li>
      <a href="lec16.html">Principal components and factor analyses</a>
    </li>
    <li>
      <a href="lec17.html">MANOVA and discriminant analysis</a>
    </li>
    <li>
      <a href="lec18.html">Multivariate distances and cluster analysis</a>
    </li>
    <li>
      <a href="lec19.html">High-resolution and high-dimension data</a>
    </li>
    <li>
      <a href="lec20.html">Analysis and visualization of large raster data sets</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Exercises</li>
    <li>
      <a href="ex01.html">Exercise 01 -- Getting R and RStudio</a>
    </li>
    <li>
      <a href="ex02.html">Exercise 02 -- Univariate plots</a>
    </li>
    <li>
      <a href="ex03.html">Exercise 03 -- Bivariate plots and descriptive statistics</a>
    </li>
    <li>
      <a href="ex04.html">Exercise 04 -- Multivariate plots</a>
    </li>
    <li>
      <a href="ex05.html">Exercise 05 -- Data wrangling and matrix algebra</a>
    </li>
    <li>
      <a href="ex06.html">Exercise 06 -- CI's, t-tests, ANOVA</a>
    </li>
    <li>
      <a href="ex07.html">Exercise 07 -- Regression analysis</a>
    </li>
    <li>
      <a href="ex08.html">Exercise 08 -- Multivariate analysis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="packages-and-data.html">Packages and data</a>
    </li>
    <li>
      <a href="vm_inst.html">Virtual machine instructions</a>
    </li>
    <li>
      <a href="readings.html">Readings</a>
    </li>
    <li>
      <a href="datasets.html">Datasets</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">More regression analysis</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li><a href="#fitting-a-multiple-regression-equation"><span class="toc-section-number">2</span> Fitting a multiple regression equation</a></li>
<li><a href="#regression-assumptions"><span class="toc-section-number">3</span> Regression Assumptions</a><ul>
<li><a href="#consequences-of-assumption-violations"><span class="toc-section-number">3.1</span> Consequences of assumption violations</a></li>
</ul></li>
<li><a href="#testing-for-assumption-violations-with-diagnostic-analyses"><span class="toc-section-number">4</span> Testing for assumption violations with diagnostic analyses</a><ul>
<li><a href="#example-1-no-major-issues"><span class="toc-section-number">4.1</span> Example 1 – no major issues</a></li>
<li><a href="#example-2-non-significant-predictor"><span class="toc-section-number">4.2</span> Example 2 – non-significant predictor</a></li>
<li><a href="#example-3-outliers-present"><span class="toc-section-number">4.3</span> Example 3 – outliers present</a></li>
<li><a href="#example-4-outliers-and-an-additional-predictor"><span class="toc-section-number">4.4</span> Example 4 – outliers and an additional predictor</a></li>
<li><a href="#example-5-heteroscedasticity-non-normality-of-the-residual"><span class="toc-section-number">4.5</span> Example 5 – heteroscedasticity (non-normality) of the residual</a></li>
<li><a href="#example-6-nonlinear-relationships"><span class="toc-section-number">4.6</span> Example 6 – nonlinear relationships</a></li>
<li><a href="#example-7-transformation"><span class="toc-section-number">4.7</span> Example 7 – transformation</a></li>
<li><a href="#example-8-fitting-a-nonlinear-quadratic-function"><span class="toc-section-number">4.8</span> Example 8 – fitting a nonlinear (quadratic) function</a></li>
<li><a href="#example-9-model-inadequacy-due-to-a-missing-predictor"><span class="toc-section-number">4.9</span> Example 9 – model inadequacy due to a missing predictor</a></li>
</ul></li>
<li><a href="#an-example-of-iterative-diagnostic-analysis"><span class="toc-section-number">5</span> An example of iterative diagnostic analysis</a><ul>
<li><a href="#inspection-of-the-data"><span class="toc-section-number">5.1</span> Inspection of the data</a></li>
<li><a href="#spatial-autocorrelation-of-july-temperature-values"><span class="toc-section-number">5.2</span> Spatial autocorrelation of July temperature values</a></li>
<li><a href="#a-naive-model"><span class="toc-section-number">5.3</span> A “naive” model</a></li>
<li><a href="#second-model-with-transformed-predictors"><span class="toc-section-number">5.4</span> Second model, with transformed predictors</a></li>
<li><a href="#all-possible-subsets-regression"><span class="toc-section-number">5.5</span> All possible subsets regression</a></li>
</ul></li>
<li><a href="#another-example-dummy-variable-regression"><span class="toc-section-number">6</span> Another example – dummy-variable regression</a><ul>
<li><a href="#look-at-the-data"><span class="toc-section-number">6.1</span> Look at the data</a></li>
<li><a href="#first-regression-all-data"><span class="toc-section-number">6.2</span> First regression, all data</a></li>
<li><a href="#dummy-variable-regression-with-country-as-a-predictor"><span class="toc-section-number">6.3</span> Dummy variable regression, with Country as a predictor</a></li>
<li><a href="#dummy-variable-regression-with-both-slope-and-intercept-varying-by-country"><span class="toc-section-number">6.4</span> Dummy-variable regression with both slope and intercept varying by Country</a></li>
</ul></li>
<li><a href="#readings"><span class="toc-section-number">7</span> Readings</a></li>
</ul>
</div>

<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>
<span style="color: #00cc00;">NOTE: This page has been revised for Spring 2020, but may undergo further edits.</span>
</p>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>Multiple regression is (conceptually) a simple extension of bivariate regression, in which the influence of more than one predictor variable on the response can be estimated. For the case with two predictor variables, the analysis can be thought of as involving the fitting of a plane (as opposed to a line in the bivariate regression case), and the equations for the OLS estimates of the regression equations are only a little more complicated algebraically. For three or more predictors, the algebra is also quite simple, but requires the use of matrix algebra.</p>
<p>A couple of illustrations jointly describe the idea of fitting a plane:</p>
<ul>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/images/nwk7_1.gif">fitting a plane using two predictor variables</a></li>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/images/mreg.gif">one data point and its deviation from the regression plane or response surface</a></li>
</ul>
</div>
<div id="fitting-a-multiple-regression-equation" class="section level1">
<h1><span class="header-section-number">2</span> Fitting a multiple regression equation</h1>
<p>The mathematics behind multiple regression analysis is more complicated than that for bivariate regression, but can be elegantly presented using matrix algebra</p>
<ul>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/topics/matrix.pdf">matrix algebra</a></li>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/topics/matreg.pdf">regression analysis in matrix algebra terms</a></li>
</ul>
<p>The following example provide a short illustration of the use of matrix algebra to obtain the regression coefficients.<br />
The example data set for illustrating the use of regression diagnostics <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/csv/regrex3.csv">[regrex3.csv]</a> is used here, in particular, the multiple regression using <code>x1</code> and <code>x2</code> as predictors for the response variable <code>y5</code></p>
<p>First, take a look at the different variables in the example data set.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="co"># regrex3</span></a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">attach</span>(regrex3)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">summary</span>(regrex3)</a></code></pre></div>
<pre><code>##     Obs.no.             x1                x2               y1               y2               y3        
##  Min.   :  1.00   Min.   : 0.2076   Min.   :-9.794   Min.   :-7.580   Min.   :-6.739   Min.   :-7.735  
##  1st Qu.: 25.75   1st Qu.: 7.6887   1st Qu.:16.850   1st Qu.: 2.104   1st Qu.: 2.580   1st Qu.: 1.761  
##  Median : 50.50   Median :15.1511   Median :27.546   Median :10.098   Median :10.002   Median :10.487  
##  Mean   : 50.50   Mean   :14.0750   Mean   :28.468   Mean   : 9.513   Mean   : 9.513   Mean   : 9.473  
##  3rd Qu.: 75.25   3rd Qu.:20.4470   3rd Qu.:40.138   3rd Qu.:17.263   3rd Qu.:16.819   3rd Qu.:17.126  
##  Max.   :100.00   Max.   :24.9525   Max.   :63.861   Max.   :24.217   Max.   :24.459   Max.   :24.168  
##        y4               y5         
##  Min.   :-2.097   Min.   : -8.455  
##  1st Qu.: 2.256   1st Qu.: 45.818  
##  Median : 9.483   Median : 76.446  
##  Mean   : 9.716   Mean   : 73.884  
##  3rd Qu.:16.588   3rd Qu.:102.690  
##  Max.   :24.217   Max.   :150.621</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">cbind</span>(y5,x1,x2))</a></code></pre></div>
<pre><code>##            y5      x1      x2
## [1,]  99.4237 17.6403 39.2009
## [2,]  47.8476  9.3786 20.2735
## [3,]  89.1535 20.0313 33.7959
## [4,] 143.1316 23.4556 48.6115
## [5,] 124.6998 24.4938 47.3454
## [6,]  51.5796  8.8475 18.0954</code></pre>
<p>Create an <em>n</em> row by 1 column matrix (i.e. a column vector) called <strong>y</strong>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="co"># create the column vector y</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2">n &lt;-<span class="st"> </span><span class="kw">length</span>(y5)</a>
<a class="sourceLine" id="cb5-3" data-line-number="3">y &lt;-<span class="st"> </span><span class="kw">matrix</span>(y5, <span class="dt">nrow=</span>n, <span class="dt">ncol=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb5-4" data-line-number="4"><span class="kw">dim</span>(y)</a></code></pre></div>
<pre><code>## [1] 100   1</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">head</span>(y)</a></code></pre></div>
<pre><code>##          [,1]
## [1,]  99.4237
## [2,]  47.8476
## [3,]  89.1535
## [4,] 143.1316
## [5,] 124.6998
## [6,]  51.5796</code></pre>
<p>Create an <em>n</em> row by <em>p</em>+1 matrix, <strong>X</strong>, with 1’s in the first column, and <code>x1</code> and <code>x2</code> in the second and third columns:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="co"># create the predictor-variable matrix</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">X &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>,n),x1,x2), <span class="dt">nrow=</span>n, <span class="dt">ncol=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="kw">dim</span>(X)</a></code></pre></div>
<pre><code>## [1] 100   3</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">head</span>(X)</a></code></pre></div>
<pre><code>##      [,1]    [,2]    [,3]
## [1,]    1 17.6403 39.2009
## [2,]    1  9.3786 20.2735
## [3,]    1 20.0313 33.7959
## [4,]    1 23.4556 48.6115
## [5,]    1 24.4938 47.3454
## [6,]    1  8.8475 18.0954</code></pre>
<p>Now use matrix algebra to calculate <strong>b</strong>, the <em>p</em>+1 row by 1 column matrix (e.g. a column vector) of regression coefficients, <em>b</em><sub>0</sub>, <em>b</em><sub>1</sub> and <em>b</em><sub>2</sub>: <strong>b</strong> = (<strong>X’X</strong>)<sup>-1</sup><strong>X’y</strong>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="co"># calculate the regression coefficients</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2">b &lt;-<span class="st"> </span><span class="kw">solve</span>(<span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X) <span class="op">%*%</span><span class="st"> </span>(<span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>y)</a>
<a class="sourceLine" id="cb13-3" data-line-number="3"><span class="kw">print</span>(b)</a></code></pre></div>
<pre><code>##           [,1]
## [1,] 3.4159624
## [2,] 0.9241464
## [3,] 2.0184663</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">dim</span>(b)</a></code></pre></div>
<pre><code>## [1] 3 1</code></pre>
<p>The matrix functions and operators used in the above expression include <code>t()</code>, which transposes a matrix, <code>%*%</code>, which is the matrix multiplication operator, and <code>solve()</code>, which inverts a matrix.</p>
<p>Compare these values with those obtained using the <code>lm()</code> function:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="co"># linear model with lm()</span></a>
<a class="sourceLine" id="cb17-2" data-line-number="2">lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y5 <span class="op">~</span><span class="st"> </span>x1<span class="op">+</span>x2, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb17-3" data-line-number="3">lm1</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y5 ~ x1 + x2, data = regrex3)
## 
## Coefficients:
## (Intercept)           x1           x2  
##      3.4160       0.9241       2.0185</code></pre>
<p>Now calculate the fitted values (<em>y-hats</em>), i.e. <span class="math inline">\(\mathbf{\widehat{y}}\)</span> = <strong>Xb</strong>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="co"># matrix fitted values</span></a>
<a class="sourceLine" id="cb19-2" data-line-number="2">yhat &lt;-<span class="st"> </span>X <span class="op">%*%</span><span class="st"> </span>b</a></code></pre></div>
<p>and compare these with those obtained using the <code>lm()</code> function</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">cbind</span>(yhat,lm1<span class="op">$</span>fitted.values))</a></code></pre></div>
<pre><code>##        [,1]      [,2]
## 1  98.84388  98.84388
## 2  53.00454  53.00454
## 3  90.14370  90.14370
## 4 123.21305 123.21305
## 5 121.61691 121.61691
## 6  48.11730  48.11730</code></pre>
<p>In addition to being able to efficiently represent the derivation of terms and thier properties in regression analysis in general, matrix algebra also provides a an efficient way of doing the actual calculations.</p>
<p><a href="lec13.html">[Back to top]</a></p>
</div>
<div id="regression-assumptions" class="section level1">
<h1><span class="header-section-number">3</span> Regression Assumptions</h1>
<p>The basic regression model (as well as more complicated ones) have certain underlying assumptions, violations of which have an impact on the optimality of the fitted model, i.e., the extent to which the model and its parameters represent the best model that can be fit, that is, the one that performs the best in the tasks of representing the relationship between the response variable and the predictor variable(s), or predicting future values of the response variable given new values of the predictor variables.</p>
<p>The main assumptions that underlie regression analysis:</p>
<ul>
<li>the prediction errors or residuals are assumed to be independent, identically normally distributed random variables, with a mean of 0 and a standard deviation of <em>s</em>,</li>
<li>the <em>X</em>’s (predictor or independent variables) are known without error,</li>
<li>the <em>X</em>’s are not correlated.</li>
<li>the correct model has been specified (i.e. the right predictors have been included in the model.</li>
</ul>
<p>If the assumptions are not violated, then the Gauss-Markov theorem indicates that the usual OLS estimates are optimal in the sense of being unbiased and having minimum variance. If one or more of the assumptions are violated, then estimated regression coefficients may be biased (i.e. they may be systematically in error), and not minimum variance (i.e. there may be more uncertainty in the coefficients than is apparent from the results).</p>
<div id="consequences-of-assumption-violations" class="section level2">
<h2><span class="header-section-number">3.1</span> Consequences of assumption violations</h2>
<p>If the assumptions are violated, then there may be two consequences–the estimated coefficients may be biased (i.e. systematically wrong), and they may longer have minimum variance (i.e. their uncertainty increases).</p>
<ul>
<li>the notion of variability of the regression coefficients</li>
<li>illustrations using repeated simulations of data sets with built-in assumption violations <a href="https://pjbartlein.github.io/GeogDataAnalysis/images/violate1.gif">[examples]</a>, <a href="https://pjbartlein.github.io/GeogDataAnalysis/images/violate2.gif">[solutions]</a></li>
</ul>
<p><a href="lec13.html">[Back to top]</a></p>
</div>
</div>
<div id="testing-for-assumption-violations-with-diagnostic-analyses" class="section level1">
<h1><span class="header-section-number">4</span> Testing for assumption violations with diagnostic analyses</h1>
<p>There are several ways to test whether the assumptions that underlie regression analysis have been violated. As might be expected, these include analytical methods, in which the values of particular test statistics are computed and compared with appropriate reference distributions, and graphical methods, which are often easier to implement (and just as informative).</p>
<p>A good way to understand the way in which the various statistics and diagnostic plots allow one to examine the reqression equation, its goodness-of-fit, and a to assess the possibility of assumption violations is to design-in various assumption violations and issues, and compare the results to a regression analysis without issues.</p>
<p>An example data set for illustrating the use of regression diagnostics <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/csv/regrex3.csv">[regrex3.csv]</a> First, take a look at the different variables in the example data set.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="co"># regrex3</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="kw">summary</span>(regrex3)</a></code></pre></div>
<pre><code>##     Obs.no.             x1                x2               y1               y2               y3        
##  Min.   :  1.00   Min.   : 0.2076   Min.   :-9.794   Min.   :-7.580   Min.   :-6.739   Min.   :-7.735  
##  1st Qu.: 25.75   1st Qu.: 7.6887   1st Qu.:16.850   1st Qu.: 2.104   1st Qu.: 2.580   1st Qu.: 1.761  
##  Median : 50.50   Median :15.1511   Median :27.546   Median :10.098   Median :10.002   Median :10.487  
##  Mean   : 50.50   Mean   :14.0750   Mean   :28.468   Mean   : 9.513   Mean   : 9.513   Mean   : 9.473  
##  3rd Qu.: 75.25   3rd Qu.:20.4470   3rd Qu.:40.138   3rd Qu.:17.263   3rd Qu.:16.819   3rd Qu.:17.126  
##  Max.   :100.00   Max.   :24.9525   Max.   :63.861   Max.   :24.217   Max.   :24.459   Max.   :24.168  
##        y4               y5         
##  Min.   :-2.097   Min.   : -8.455  
##  1st Qu.: 2.256   1st Qu.: 45.818  
##  Median : 9.483   Median : 76.446  
##  Mean   : 9.716   Mean   : 73.884  
##  3rd Qu.:16.588   3rd Qu.:102.690  
##  Max.   :24.217   Max.   :150.621</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="co"># matrix plot of the data</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="kw">plot</span>(regrex3[,<span class="dv">2</span><span class="op">:</span><span class="dv">8</span>])</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag01-1.png" width="2100" /></p>
<p>There are two potential predictor variables <code>x1</code> and <code>x2</code>, and five potential responses, each with particular issues or assumption violations. The idea here is to examine the summary output and diagnostic plots for each regression, and compare them to a case (the first regression) where there are no major issues.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="co"># set up for plotting</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a></code></pre></div>
<div id="example-1-no-major-issues" class="section level2">
<h2><span class="header-section-number">4.1</span> Example 1 – no major issues</h2>
<p>Here’s an inital regression, that shows no major issues:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="co"># first regression</span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2">regr_y1x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y1 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb26-3" data-line-number="3"><span class="kw">summary</span>(regr_y1x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y1 ~ x1, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1266 -0.5178 -0.1048  0.5725  2.4955 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7.56853    0.19743  -38.33   &lt;2e-16 ***
## x1           1.21362    0.01249   97.17   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8986 on 98 degrees of freedom
## Multiple R-squared:  0.9897, Adjusted R-squared:  0.9896 
## F-statistic:  9441 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb28-2" data-line-number="2"><span class="kw">plot</span>(regr_y1x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;First Regression&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag03-1.png" width="2100" /></p>
</div>
<div id="example-2-non-significant-predictor" class="section level2">
<h2><span class="header-section-number">4.2</span> Example 2 – non-significant predictor</h2>
<p>One of the most common issues in regression equations is the inclusion of a predictor that is not significant, in the sense that the <code>t-test</code> of the null hypothesis that the slope parameter for that predictor is zero is not significant (i.e. there is no support for rejecting that hypthesis). Here’s a example, where <code>x2</code> is not significant:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="co"># add a second predictor</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2">regr_y1x1x2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y1 <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span>x2, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb29-3" data-line-number="3"><span class="kw">summary</span>(regr_y1x1x2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y1 ~ x1 + x2, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1397 -0.5306 -0.1069  0.5713  2.4898 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7.573018   0.200055 -37.855   &lt;2e-16 ***
## x1           1.209268   0.027783  43.526   &lt;2e-16 ***
## x2           0.002309   0.013152   0.176    0.861    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9031 on 97 degrees of freedom
## Multiple R-squared:  0.9897, Adjusted R-squared:  0.9895 
## F-statistic:  4674 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw">plot</span>(regr_y1x1x2, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Two Predictors&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag04-1.png" width="2100" /></p>
</div>
<div id="example-3-outliers-present" class="section level2">
<h2><span class="header-section-number">4.3</span> Example 3 – outliers present</h2>
<p>Outliers frequently arise, from mechanical (coding or recording), sampling (i.e. selection of the cases or locations), or from the simple inclusion of data points that are “outside” of the domain of interest. The third example shows how the outliers can be identified in the diagnostic plots. Cases 79 and 49 standout.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="co"># outliers</span></a>
<a class="sourceLine" id="cb32-2" data-line-number="2">regr_y2x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y2 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb32-3" data-line-number="3"><span class="kw">summary</span>(regr_y2x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y2 ~ x1, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4172 -0.9379 -0.2050  0.5098  6.1841 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7.45078    0.28177  -26.44   &lt;2e-16 ***
## x1           1.20525    0.01783   67.61   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.282 on 98 degrees of freedom
## Multiple R-squared:  0.979,  Adjusted R-squared:  0.9788 
## F-statistic:  4572 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb34-2" data-line-number="2"><span class="kw">plot</span>(regr_y2x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Outliers&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/diag05-1.png" width="2100" /></p>
</div>
<div id="example-4-outliers-and-an-additional-predictor" class="section level2">
<h2><span class="header-section-number">4.4</span> Example 4 – outliers and an additional predictor</h2>
<p>Sometimes the existence of outliers can be traced to the omission of a potentially important predictor. In this case, the inclusion of <code>x2</code> does not eliminate the outliers, and as before, the slope coefficient of <code>x2</code> is not significant.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="co"># no help for outliers</span></a>
<a class="sourceLine" id="cb35-2" data-line-number="2">regr_y2x1x2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y2 <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span>x2, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb35-3" data-line-number="3"><span class="kw">summary</span>(regr_y2x1x2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y2 ~ x1 + x2, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4508 -0.8600 -0.2018  0.4924  6.1845 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7.463675   0.285371 -26.154   &lt;2e-16 ***
## x1           1.192732   0.039631  30.096   &lt;2e-16 ***
## x2           0.006642   0.018760   0.354    0.724    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.288 on 97 degrees of freedom
## Multiple R-squared:  0.979,  Adjusted R-squared:  0.9786 
## F-statistic:  2265 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb37-2" data-line-number="2"><span class="kw">plot</span>(regr_y2x1x2, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Still Outliers&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/diag06-1.png" width="2100" /></p>
</div>
<div id="example-5-heteroscedasticity-non-normality-of-the-residual" class="section level2">
<h2><span class="header-section-number">4.5</span> Example 5 – heteroscedasticity (non-normality) of the residual</h2>
<p>Heteroscedasticity, or inhomogeneity of variance can arise several ways: it can be “inherited” from the response variable in cases where that variable is not completely “explained” by the predictor variable(s), and it can also signal issues with the structure of the model. In practice, heterscedastic residuals increase the variability of the regression parameter estimates, which means that we can be less confident that the “true” values of the coeffiecients have been estimated. Heteroscedasticity is signaled by the diagnostic plots, in particular “megaphone” patterns in the residual scatterplot, and “doglegs” in the normal probability plots.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="co"># heteroscedasticity</span></a>
<a class="sourceLine" id="cb38-2" data-line-number="2">regr_y3x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y3 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb38-3" data-line-number="3"><span class="kw">summary</span>(regr_y3x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y3 ~ x1, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8574 -0.2395 -0.0763  0.2572  2.2611 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -7.828320   0.135390  -57.82   &lt;2e-16 ***
## x1           1.229227   0.008565  143.51   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6162 on 98 degrees of freedom
## Multiple R-squared:  0.9953, Adjusted R-squared:  0.9952 
## F-statistic: 2.06e+04 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb40-2" data-line-number="2"><span class="kw">plot</span>(regr_y3x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Heteroscedasticity&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag07-1.png" width="2100" /></p>
</div>
<div id="example-6-nonlinear-relationships" class="section level2">
<h2><span class="header-section-number">4.6</span> Example 6 – nonlinear relationships</h2>
<p>Standard regrssion analyses attempt to fit <em>linear</em> relationships among variables, and often that’s not a reasonable assumption to make. This example illustrates how nonlinear relationships are exposed by the residual diagnostic plots (if they haven’t already been recognized), in particular by well-organized patterns in the residual scatterplot and leverage plot.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="co"># nonlinear relationship</span></a>
<a class="sourceLine" id="cb41-2" data-line-number="2">regr_y4x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y4 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb41-3" data-line-number="3"><span class="kw">summary</span>(regr_y4x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y4 ~ x1, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8042 -1.0126 -0.1873  0.7448  3.4770 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5.70564    0.28650  -19.91   &lt;2e-16 ***
## x1           1.09567    0.01812   60.45   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.304 on 98 degrees of freedom
## Multiple R-squared:  0.9739, Adjusted R-squared:  0.9736 
## F-statistic:  3655 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb43-2" data-line-number="2"><span class="kw">plot</span>(regr_y4x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Nonlinear Relationship&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag08-1.png" width="2100" /></p>
</div>
<div id="example-7-transformation" class="section level2">
<h2><span class="header-section-number">4.7</span> Example 7 – transformation</h2>
<p>The usual first-order strategy for dealing with heteroscedasticity and non-linearity is to transform one or another of the variables (or both) in a bivariate regression. Here, the values of <code>y4</code> are transformed buy taking their (base 10) logarithms. Because the logs of 0 and negative numbers are undefined, the values of <code>y4</code> are adjusted to make them nonzero and positive. However, there are still major problems signalled by the regression diagnostic plots.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="co"># alternative nonlinear log(y4) ~ x1</span></a>
<a class="sourceLine" id="cb44-2" data-line-number="2">regr_logy4x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log10</span>(y4<span class="op">-</span><span class="kw">min</span>(y4) <span class="op">+</span><span class="st"> </span><span class="fl">0.001</span>) <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb44-3" data-line-number="3"><span class="kw">summary</span>(regr_logy4x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log10(y4 - min(y4) + 0.001) ~ x1, data = regrex3)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.96720 -0.10553  0.07042  0.18018  0.23304 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.113399   0.076959  -1.473    0.144    
## x1           0.069853   0.004869  14.348   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3503 on 98 degrees of freedom
## Multiple R-squared:  0.6775, Adjusted R-squared:  0.6742 
## F-statistic: 205.9 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb46-2" data-line-number="2"><span class="kw">plot</span>(regr_logy4x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Transformation of y&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag09-1.png" width="2100" /></p>
</div>
<div id="example-8-fitting-a-nonlinear-quadratic-function" class="section level2">
<h2><span class="header-section-number">4.8</span> Example 8 – fitting a nonlinear (quadratic) function</h2>
<p>An alternative approach to “linearizing” a relationship is to fit a quadratic polynomial (i.e containing the terms <em>x</em> and <em>x<sup>2</sup></em>) to the data. The <code>I()</code> function indicates that the term <code>x1^2</code> should be treated as is, and is not part of the “formula” in the <code>lm()</code> function.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="co"># alternative nonlinear (quadratic) y4 ~ x1, x1^2</span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2">regr_y4x1x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y4 <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="kw">I</span>(x1<span class="op">^</span><span class="dv">2</span>), <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb47-3" data-line-number="3"><span class="kw">summary</span>(regr_y4x1x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y4 ~ x1 + I(x1^2), data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.6013 -0.1507 -0.0232  0.1507  0.6944 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.1100971  0.0912787  -23.12   &lt;2e-16 ***
## x1           0.3372719  0.0156315   21.58   &lt;2e-16 ***
## I(x1^2)      0.0283312  0.0005688   49.81   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2542 on 97 degrees of freedom
## Multiple R-squared:  0.999,  Adjusted R-squared:  0.999 
## F-statistic: 4.93e+04 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb49-2" data-line-number="2"><span class="kw">plot</span>(regr_y4x1x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Quadratic Polynomial&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag10-1.png" width="2100" /></p>
<p>This equation fits much better than the previous one, and show no major problems</p>
</div>
<div id="example-9-model-inadequacy-due-to-a-missing-predictor" class="section level2">
<h2><span class="header-section-number">4.9</span> Example 9 – model inadequacy due to a missing predictor</h2>
<p>Here’s an example regression, where the data were generated by an equation that included <code>x2</code>. Note that there are slight megaphone and dog-leg patterns in the residual plots.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="co"># model inadequacy, missing predictor</span></a>
<a class="sourceLine" id="cb50-2" data-line-number="2">regr_y5x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(y5 <span class="op">~</span><span class="st"> </span>x1, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb50-3" data-line-number="3"><span class="kw">summary</span>(regr_y5x1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y5 ~ x1, data = regrex3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.572  -8.277   1.015   9.946  37.444 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.3358     3.4579   2.121   0.0364 *  
## x1            4.7281     0.2188  21.614   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.74 on 98 degrees of freedom
## Multiple R-squared:  0.8266, Adjusted R-squared:  0.8248 
## F-statistic: 467.2 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb52-2" data-line-number="2"><span class="kw">plot</span>(regr_y5x1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Missing Predictor&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag11-1.png" width="2100" /></p>
<p>The typical way of examining the possibility that the inclusion of another predictor may be warrented, is to examine correlations between the residual, and other potential predictors. In this case it looks like the residuals are correlated with <code>x2</code>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="co"># check for correlation between residuals and other predictors</span></a>
<a class="sourceLine" id="cb53-2" data-line-number="2"><span class="kw">par</span>(oldpar)</a>
<a class="sourceLine" id="cb53-3" data-line-number="3"><span class="kw">plot</span>(regr_y5x1<span class="op">$</span>residual <span class="op">~</span><span class="st"> </span>regrex3<span class="op">$</span>x2)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag12-1.png" width="2100" /></p>
<p>When <code>x2</code> is included in the model, the various diagnostic checks show no major issues, except possibly a some extra influence by points 100, 24 and 4.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="co"># last model, y5 ~ x1 and x2</span></a>
<a class="sourceLine" id="cb54-2" data-line-number="2">regr_y5x1x2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y5 <span class="op">~</span><span class="st"> </span>x1<span class="op">+</span>x2, <span class="dt">data=</span>regrex3)</a>
<a class="sourceLine" id="cb54-3" data-line-number="3"><span class="kw">summary</span>(regr_y5x1x2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y5 ~ x1 + x2, data = regrex3)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.1177  -4.2447  -0.8552   4.5699  19.9186 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.4160     1.6005   2.134   0.0353 *  
## x1            0.9241     0.2223   4.158 6.94e-05 ***
## x2            2.0185     0.1052  19.185  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.224 on 97 degrees of freedom
## Multiple R-squared:  0.9638, Adjusted R-squared:  0.9631 
## F-statistic:  1292 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb56-2" data-line-number="2"><span class="kw">plot</span>(regr_y5x1x2, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="dt">main=</span><span class="st">&quot;Two Predictors&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/rdiag13-1.png" width="2100" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<p><a href="lec13.html">[Back to top]</a></p>
</div>
</div>
<div id="an-example-of-iterative-diagnostic-analysis" class="section level1">
<h1><span class="header-section-number">5</span> An example of iterative diagnostic analysis</h1>
<p><em>Multiple regression</em> is the extension of bivariate regression to the case where there are multiple predictor variables. (The case where there are multiple predictors and multiple responses is generally referred to as <em>multivariate regression</em>.) This example illustrates the development of a “transfer function” a not-ideally named approach for reconstructing past climates from fossil pollen data. The idea is to build a regression equation that illustrates the relationship between a particular climate variable as the response to a number of pollen variables as predictors using modern pollen and climate data, and then to apply this relationship “downcore” to fossil-pollen data (plugging in pollen, and getting out climate). The data set has a few issues that often arise in practice, including the fact that the pollen variables (pollen types) are themselves correlated (violating the OLS assumption of no collinearity), and the climate variables are highly spatially autocorrelated, which could lead to autocorrelation in the residuals (violating another OLS assumption, homogeneity of variance of the residual). The relationships between the climate and pollen variables are often curvilinear (violating yet another assumption, correct specification of the model).</p>
<p>These issues will be examined using the standard diagnostic plots, as well as the Moran statistic for assessing spatial autocorrelation, and the curvilinearity/collinearity issue will be handled by transformation and “best subsets” predictor selection.</p>
<p>Here are the data <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/csv/midwtf2.csv">[midwtf2]</a>, and the components of a shape file for mapping the data and results <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/midwotl.dbf">[.dbf]</a> <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/midwotl.shx">[.shx]</a> <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/midwotl.shp">[.shp]</a> <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/midwotl.prj">[.prj]</a></p>
<p>Load some libraries.</p>
<p>Load some packages, and attach the data frame:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="co"># libraries</span></a>
<a class="sourceLine" id="cb58-2" data-line-number="2"><span class="kw">library</span>(sf)</a>
<a class="sourceLine" id="cb58-3" data-line-number="3"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb58-4" data-line-number="4"><span class="kw">library</span>(RColorBrewer)</a>
<a class="sourceLine" id="cb58-5" data-line-number="5"><span class="kw">library</span>(spdep)</a>
<a class="sourceLine" id="cb58-6" data-line-number="6"><span class="kw">library</span>(leaps)</a>
<a class="sourceLine" id="cb58-7" data-line-number="7"><span class="kw">library</span>(ggplot2)</a></code></pre></div>
<p>The pollen variables with numbers in their names (e.g. <code>Querc.25</code>) are transformation of the original pollen variables (<code>Quercus</code>) constructed using “power function” transformations (i.e. <code>Querc.25 &lt;- Quercus^0.25</code>) to linearize the relationships between climate and pollen (see the scatter diagrams below). The transformation parameters were chosen by inspecting individual scatter diagrams between a climate variable and pollen variable.</p>
<div id="inspection-of-the-data" class="section level2">
<h2><span class="header-section-number">5.1</span> Inspection of the data</h2>
<p><em>Always</em> look at the data before running any kind of analysis. Begin by mapping the data. Get the point locations of each modern pollen (and climate) sample, and plot the distance-weighted neighbors (for calculating the Moran statistic) using a distance threshold of 100km</p>
<p>Read a shapefile of outlines for the region</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1"><span class="co"># read a state outline shape file</span></a>
<a class="sourceLine" id="cb59-2" data-line-number="2">shapefile &lt;-<span class="st"> &quot;/Users/bartlein/Documents/geog495/data/shp/midwotl.shp&quot;</span></a>
<a class="sourceLine" id="cb59-3" data-line-number="3">midwotl_sf &lt;-<span class="st"> </span><span class="kw">st_read</span>(shapefile)</a></code></pre></div>
<pre><code>## Reading layer `midwotl&#39; from data source `/Users/bartlein/Documents/geog495/data/shp/midwotl.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 26 features and 1 field
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -95.35374 ymin: 39.78763 xmax: -83.70557 ymax: 50.80387
## CRS:            NA</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1">midwotl_sf</a></code></pre></div>
<pre><code>## Simple feature collection with 26 features and 1 field
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -95.35374 ymin: 39.78763 xmax: -83.70557 ymax: 50.80387
## CRS:            NA
## First 10 features:
##    ID                       geometry
## 1   1 POLYGON ((-94.91827 39.7876...
## 2   2 POLYGON ((-95.3087 39.99941...
## 3   3 POLYGON ((-91.44875 40.3719...
## 4   4 POLYGON ((-84.80794 39.7876...
## 5   5 POLYGON ((-84.79038 41.6974...
## 6   6 POLYGON ((-87.79738 42.4891...
## 7   7 POLYGON ((-91.73037 43.4995...
## 8   8 POLYGON ((-87.03452 45.2904...
## 9   9 POLYGON ((-83.70557 45.4088...
## 10 10 POLYGON ((-83.70557 45.9463...</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1"><span class="kw">plot</span>(midwotl_sf) <span class="co"># plot the outline</span></a></code></pre></div>
<p><img src="lec13_files/figure-html/unnamed-chunk-1-1.png" width="2100" /></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">st_geometry</span>(midwotl_sf), <span class="dt">axes =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/unnamed-chunk-1-2.png" width="2100" /></p>
<p>Read the data, if it’s not already in the workspace:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="co"># read the data file (if not already in the workspace)</span></a>
<a class="sourceLine" id="cb65-2" data-line-number="2">csv_path &lt;-<span class="st"> &quot;/Users/bartlein/Documents/geog495/data/csv/midwtf2&quot;</span></a>
<a class="sourceLine" id="cb65-3" data-line-number="3">midwtf2 &lt;-<span class="st"> </span><span class="kw">read.csv</span>(csv_path)</a></code></pre></div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">attach</span>(midwtf2)</a>
<a class="sourceLine" id="cb66-2" data-line-number="2"><span class="kw">names</span>(midwtf2)</a></code></pre></div>
<pre><code>##  [1] &quot;seqnum&quot;     &quot;latitude&quot;   &quot;longitud&quot;   &quot;tmeanjul&quot;   &quot;tmeanyr&quot;    &quot;precpyr&quot;    &quot;Picea&quot;     
##  [8] &quot;Abies&quot;      &quot;Juniper&quot;    &quot;Pinus&quot;      &quot;Betula&quot;     &quot;Fraxinus&quot;   &quot;Quercus&quot;    &quot;Ulmus&quot;     
## [15] &quot;Acer&quot;       &quot;Juglans&quot;    &quot;Carya&quot;      &quot;Tsuga&quot;      &quot;Fagus&quot;      &quot;Alnus&quot;      &quot;Herbsum&quot;   
## [22] &quot;Picea.50&quot;   &quot;Abies.100&quot;  &quot;Junip.100&quot;  &quot;Pinus.100&quot;  &quot;Betula.50&quot;  &quot;Frax.15&quot;    &quot;Querc.25&quot;  
## [29] &quot;Ulmus.25&quot;   &quot;Acer.100&quot;   &quot;Juglans.25&quot; &quot;Carya.25&quot;   &quot;Tsuga.100&quot;  &quot;Fagus.100&quot;  &quot;Alnus.100&quot; 
## [36] &quot;Herbs.25&quot;</code></pre>
<p>Plot the network of sites, and also get distance-neighbor matrix for calculating spatial autocorrelation.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="co"># get point locations of modern data</span></a>
<a class="sourceLine" id="cb68-2" data-line-number="2">midwtf2_loc=<span class="kw">cbind</span>(longitud, latitude)</a></code></pre></div>
<p>Get the distance neighbors (i.e. the contiguity matrix <strong>W</strong>)</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1"><span class="co"># distance neighbors</span></a>
<a class="sourceLine" id="cb69-2" data-line-number="2">d &lt;-<span class="st"> </span><span class="dv">100</span> <span class="co"># points are neighbors if locations are within d km of one another</span></a>
<a class="sourceLine" id="cb69-3" data-line-number="3">midwtf2_neighbors_dist &lt;-<span class="st"> </span><span class="kw">dnearneigh</span>(midwtf2_loc, <span class="dv">0</span>, d, <span class="dt">longlat=</span><span class="ot">TRUE</span>) </a>
<a class="sourceLine" id="cb69-4" data-line-number="4"><span class="kw">plot</span>(<span class="kw">st_geometry</span>(midwotl_sf), <span class="dt">axes=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb69-5" data-line-number="5"><span class="kw">points</span>(midwtf2_loc)</a>
<a class="sourceLine" id="cb69-6" data-line-number="6"><span class="kw">plot</span>(midwtf2_neighbors_dist, midwtf2_loc, <span class="dt">add=</span><span class="ot">TRUE</span>, <span class="dt">col=</span><span class="st">&quot;magenta&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dist-1.png" width="2100" /></p>
<p>Next, examine the data set. First plot latitude, longitude, and the climate variables relative to one another (to reveal the geographical gradients in the cliamte data).</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="co"># examine the data set</span></a>
<a class="sourceLine" id="cb70-2" data-line-number="2"><span class="co"># plot lat, lon and climate variables</span></a>
<a class="sourceLine" id="cb70-3" data-line-number="3"><span class="kw">plot</span>(midwtf2[,<span class="dv">2</span><span class="op">:</span><span class="dv">6</span>])</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr04-1.png" width="2100" /></p>
<p>Now plot July temperature (the response variable here) relative to a few (untransformed) pollen types, and note the curvilinear relationships.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1"><span class="co"># plot July temperature and selected pollen types</span></a>
<a class="sourceLine" id="cb71-2" data-line-number="2"><span class="kw">plot</span>(midwtf2[,<span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">21</span>)])</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr05-1.png" width="2100" /></p>
<p>Next, plot July temperature vs. the transformed pollen types, and note how the transformations linearize the relationships.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1"><span class="co"># plot July temperature and transformed pollen </span></a>
<a class="sourceLine" id="cb72-2" data-line-number="2"><span class="kw">plot</span>(midwtf2[,<span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">22</span>,<span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">36</span>)])</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr06-1.png" width="2100" /></p>
</div>
<div id="spatial-autocorrelation-of-july-temperature-values" class="section level2">
<h2><span class="header-section-number">5.2</span> Spatial autocorrelation of July temperature values</h2>
<p>The assuption that the prediction errors or residuals are assumed to be independent, identically normally distributed random variables, is often violated in geographical or Earth-system science data sets owing to spatial or temporal autocorrelation in the dependent or response variable. If the regression model cannot explain <em>all</em> of the variation in the response model, then the autocorrelation of the response will be inhereted by the residuals or prediction errors. This inherentance will be evidenced by spatial or temporal patterns in residuals, which could be though of inforation that should be incorporated in the “systematic” component of the model.</p>
<p>In this example, spatial autocorrelation of the residuals will the issue. The <em>Moran statistic</em> is a measure of spatial autocorrelation, and in the regressions below, will be used to test for spatial pattern in the residuals as the model is gradually refined.</p>
<ul>
<li><a href="https://pjbartlein.github.io/GeogDataAnalysis/topics/moran.pdf">Moran statistic details</a></li>
</ul>
<p>To illustrate the Moran statistic, and gain an impression of the level of spatial autocorrelation in the response (as opposed to the residuals) calculate the Moran statistic for July temperature, the response. For comparison with the residuals (which should be centered on zero), we’ll convert the July temperature values to “centered” values, by subtracting the mean. We should see the amplitude of the values diminish as the “fit” gets better and better. This is consistent with the idea of the residuals having no “pattern” or systematic variation.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1"><span class="co"># ggplot2 map of temperature</span></a>
<a class="sourceLine" id="cb73-2" data-line-number="2">plotvar &lt;-<span class="st"> </span>tmeanjul</a>
<a class="sourceLine" id="cb73-3" data-line-number="3">plotvar &lt;-<span class="st"> </span>plotvar<span class="op">-</span><span class="kw">mean</span>(plotvar)</a>
<a class="sourceLine" id="cb73-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Modern Climate (mean subtracted)&quot;</span></a>
<a class="sourceLine" id="cb73-5" data-line-number="5">leglable &lt;-<span class="st"> &quot;tmeanjul (C)&quot;</span></a>
<a class="sourceLine" id="cb73-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb73-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> midwotl_sf, <span class="dt">fill=</span><span class="st">&quot;grey70&quot;</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb73-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> midwtf2, <span class="kw">aes</span>(<span class="dt">x =</span> longitud, <span class="dt">y =</span> latitude, <span class="dt">color =</span> plotvar), <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb73-9" data-line-number="9"><span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">mid=</span> <span class="st">&quot;white&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">aesthetics =</span> <span class="st">&#39;color&#39;</span>,</a>
<a class="sourceLine" id="cb73-10" data-line-number="10">                       <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="dt">by =</span> <span class="dv">1</span>), <span class="dt">guide =</span> <span class="st">&#39;colorbar&#39;</span>, <span class="dt">name =</span> leglable) <span class="op">+</span></a>
<a class="sourceLine" id="cb73-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Longitude&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Latitude&quot;</span>, <span class="dt">title =</span> plottitle) </a></code></pre></div>
<p><img src="lec13_files/figure-html/mr07-1.png" width="2100" /></p>
<p>The map shows that July temperatures are quite spatially autocorrelated, which the Moran statistic confirms.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1"><span class="co"># spatial autocorrelation of dependent variable (tmeanjul)</span></a>
<a class="sourceLine" id="cb74-2" data-line-number="2"><span class="kw">moran.test</span>(tmeanjul, <span class="dt">zero.policy=</span>T, </a>
<a class="sourceLine" id="cb74-3" data-line-number="3">     <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  tmeanjul  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 12.081, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.592512863      -0.008547009       0.002475262</code></pre>
<p>In some ways, the objective the regression analysis can be posed in terms of “taking the autocorrelation out” of July temperature.</p>
</div>
<div id="a-naive-model" class="section level2">
<h2><span class="header-section-number">5.3</span> A “naive” model</h2>
<p>The simplist model (in terms of not worrying about assumption violations, etc.) is one in which all of the potential predictor variables were included, in their “raw” or untransfomed form</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1"><span class="co"># naive model</span></a>
<a class="sourceLine" id="cb76-2" data-line-number="2">tmeanjul_lm0 &lt;-<span class="st"> </span><span class="kw">lm</span>(tmeanjul <span class="op">~</span><span class="st"> </span>Picea <span class="op">+</span><span class="st"> </span>Abies <span class="op">+</span><span class="st"> </span>Juniper</a>
<a class="sourceLine" id="cb76-3" data-line-number="3">   <span class="op">+</span><span class="st"> </span>Pinus <span class="op">+</span><span class="st"> </span>Betula <span class="op">+</span><span class="st"> </span>Fraxinus <span class="op">+</span><span class="st"> </span>Quercus <span class="op">+</span><span class="st"> </span>Ulmus</a>
<a class="sourceLine" id="cb76-4" data-line-number="4">   <span class="op">+</span><span class="st"> </span>Acer <span class="op">+</span><span class="st"> </span>Juglans <span class="op">+</span><span class="st"> </span>Carya <span class="op">+</span><span class="st"> </span>Tsuga <span class="op">+</span><span class="st"> </span>Fagus</a>
<a class="sourceLine" id="cb76-5" data-line-number="5">   <span class="op">+</span><span class="st"> </span>Alnus <span class="op">+</span><span class="st"> </span>Herbsum)</a>
<a class="sourceLine" id="cb76-6" data-line-number="6"></a>
<a class="sourceLine" id="cb76-7" data-line-number="7"><span class="kw">summary</span>(tmeanjul_lm0)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = tmeanjul ~ Picea + Abies + Juniper + Pinus + Betula + 
##     Fraxinus + Quercus + Ulmus + Acer + Juglans + Carya + Tsuga + 
##     Fagus + Alnus + Herbsum)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.45317 -0.55241  0.01733  0.46385  1.75910 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  179.508    655.531   0.274    0.785
## Picea         -1.649      6.556  -0.252    0.802
## Abies         -1.876      6.549  -0.286    0.775
## Juniper       -1.662      6.557  -0.253    0.800
## Pinus         -1.594      6.555  -0.243    0.808
## Betula        -1.619      6.554  -0.247    0.805
## Fraxinus      -1.447      6.547  -0.221    0.825
## Quercus       -1.566      6.556  -0.239    0.812
## Ulmus         -1.589      6.552  -0.243    0.809
## Acer          -1.532      6.558  -0.234    0.816
## Juglans       -1.276      6.561  -0.195    0.846
## Carya         -1.609      6.550  -0.246    0.806
## Tsuga         -1.604      6.558  -0.245    0.807
## Fagus         -1.632      6.555  -0.249    0.804
## Alnus         -1.573      6.556  -0.240    0.811
## Herbsum       -1.571      6.556  -0.240    0.811
## 
## Residual standard error: 0.7185 on 108 degrees of freedom
## Multiple R-squared:  0.8271, Adjusted R-squared:  0.8031 
## F-statistic: 34.45 on 15 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb78-2" data-line-number="2"><span class="kw">plot</span>(tmeanjul_lm0, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr10-1.png" width="2100" /></p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<p>Map the residuals from the naive model</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1"><span class="co"># ggplot2 map of residuals</span></a>
<a class="sourceLine" id="cb80-2" data-line-number="2">plotvar &lt;-<span class="st"> </span><span class="kw">residuals</span>(tmeanjul_lm0)</a>
<a class="sourceLine" id="cb80-3" data-line-number="3">plotvar &lt;-<span class="st"> </span>plotvar<span class="op">-</span><span class="kw">mean</span>(plotvar)</a>
<a class="sourceLine" id="cb80-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Naive model residuals (C)&quot;</span></a>
<a class="sourceLine" id="cb80-5" data-line-number="5">leglable &lt;-<span class="st"> &quot;residuals tmeanjul_lm0&quot;</span></a>
<a class="sourceLine" id="cb80-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb80-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> midwotl_sf, <span class="dt">fill=</span><span class="st">&quot;grey70&quot;</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> midwtf2, <span class="kw">aes</span>(<span class="dt">x =</span> longitud, <span class="dt">y =</span> latitude, <span class="dt">color =</span> plotvar), <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-9" data-line-number="9"><span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">mid=</span> <span class="st">&quot;white&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">aesthetics =</span> <span class="st">&#39;color&#39;</span>,</a>
<a class="sourceLine" id="cb80-10" data-line-number="10">                       <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dt">by =</span> <span class="dv">1</span>), <span class="dt">guide =</span> <span class="st">&#39;colorbar&#39;</span>, <span class="dt">name =</span> leglable) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Longitude&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Latitude&quot;</span>, <span class="dt">title =</span> plottitle) </a></code></pre></div>
<p><img src="lec13_files/figure-html/mr11-1.png" width="2100" /></p>
<p>… and calculate the Moran statistic for the naive model residuals:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1"><span class="co"># Moran test</span></a>
<a class="sourceLine" id="cb81-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm0), <span class="dt">zero.policy=</span>T, </a>
<a class="sourceLine" id="cb81-3" data-line-number="3">     <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm0)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 2.1997, p-value = 0.01392
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.100919178      -0.008547009       0.002476578</code></pre>
<p>There are a few troublesome issues with the naive model. The obvious one is the similarity of the standard errors of the regression coefficients, which is one of the byproducts of collinearity. Here, the pollen data are almost exactly collinear, because the pollen percentages must some to 100. (There are a few minor types omitted, so they don’t do that exactly.)</p>
<p>The extent of collinearity can be confirmed by calculating something called the “condition number” of the matrix <strong>X<sup>T</sup>X</strong> (where <strong>X</strong> is the matrix of predictor variables), which is the ratio of the largest to smallest eigenvector of <strong>X<sup>T</sup>X</strong>. This number should be small, say less than 50 or so, and it isn’t.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" data-line-number="1"><span class="kw">kappa</span>(tmeanjul_lm0)</a></code></pre></div>
<pre><code>## [1] 813270.7</code></pre>
</div>
<div id="second-model-with-transformed-predictors" class="section level2">
<h2><span class="header-section-number">5.4</span> Second model, with transformed predictors</h2>
<p>There are two approaches for dealing with collinearity here: 1) omitting some variables, and 2) repeating the regression with the transformed values of the pollen variables (which we are inclined to do anyway):</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" data-line-number="1"><span class="co"># a second model, transformed predictors</span></a>
<a class="sourceLine" id="cb85-2" data-line-number="2">tmeanjul_lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(tmeanjul <span class="op">~</span><span class="st"> </span>Picea<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Abies<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Junip<span class="fl">.100</span></a>
<a class="sourceLine" id="cb85-3" data-line-number="3">    <span class="op">+</span><span class="st"> </span>Pinus<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Betula<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Frax<span class="fl">.15</span> <span class="op">+</span><span class="st"> </span>Querc<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Ulmus<span class="fl">.25</span></a>
<a class="sourceLine" id="cb85-4" data-line-number="4">    <span class="op">+</span><span class="st"> </span>Acer<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Juglans<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Carya<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Tsuga<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Fagus<span class="fl">.100</span></a>
<a class="sourceLine" id="cb85-5" data-line-number="5">    <span class="op">+</span><span class="st"> </span>Alnus<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Herbs<span class="fl">.25</span>)</a>
<a class="sourceLine" id="cb85-6" data-line-number="6"></a>
<a class="sourceLine" id="cb85-7" data-line-number="7"><span class="kw">summary</span>(tmeanjul_lm1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = tmeanjul ~ Picea.50 + Abies.100 + Junip.100 + Pinus.100 + 
##     Betula.50 + Frax.15 + Querc.25 + Ulmus.25 + Acer.100 + Juglans.25 + 
##     Carya.25 + Tsuga.100 + Fagus.100 + Alnus.100 + Herbs.25)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.40711 -0.48675 -0.02564  0.44313  1.89582 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 18.9397674  1.1194874  16.918  &lt; 2e-16 ***
## Picea.50    -0.3453090  0.1831966  -1.885 0.062130 .  
## Abies.100   -0.3215553  0.1620875  -1.984 0.049811 *  
## Junip.100   -0.0494478  0.0479544  -1.031 0.304778    
## Pinus.100   -0.0034006  0.0068931  -0.493 0.622779    
## Betula.50   -0.2344634  0.0763430  -3.071 0.002698 ** 
## Frax.15      0.3937369  0.2116480   1.860 0.065558 .  
## Querc.25     1.0608572  0.2822012   3.759 0.000277 ***
## Ulmus.25    -0.2533915  0.2387401  -1.061 0.290889    
## Acer.100     0.0593244  0.0528028   1.124 0.263712    
## Juglans.25   0.2133503  0.1788496   1.193 0.235521    
## Carya.25     0.0045774  0.2119793   0.022 0.982812    
## Tsuga.100   -0.0002757  0.0249672  -0.011 0.991211    
## Fagus.100   -0.0584046  0.0367915  -1.587 0.115335    
## Alnus.100   -0.0011686  0.0408867  -0.029 0.977252    
## Herbs.25     0.5469401  0.2659081   2.057 0.042108 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7304 on 108 degrees of freedom
## Multiple R-squared:  0.8213, Adjusted R-squared:  0.7965 
## F-statistic:  33.1 on 15 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb87-2" data-line-number="2"><span class="kw">plot</span>(tmeanjul_lm1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr14-1.png" width="2100" /></p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<p>Map the residuals.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" data-line-number="1"><span class="co"># ggplot2 map of residuals</span></a>
<a class="sourceLine" id="cb89-2" data-line-number="2">plotvar &lt;-<span class="st"> </span><span class="kw">residuals</span>(tmeanjul_lm1)</a>
<a class="sourceLine" id="cb89-3" data-line-number="3">plotvar &lt;-<span class="st"> </span>plotvar<span class="op">-</span><span class="kw">mean</span>(plotvar)</a>
<a class="sourceLine" id="cb89-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Second model residuals (C)&quot;</span></a>
<a class="sourceLine" id="cb89-5" data-line-number="5">leglable &lt;-<span class="st"> &quot;residuals tmeanjul_lm1&quot;</span></a>
<a class="sourceLine" id="cb89-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb89-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> midwotl_sf, <span class="dt">fill=</span><span class="st">&quot;grey70&quot;</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb89-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> midwtf2, <span class="kw">aes</span>(<span class="dt">x =</span> longitud, <span class="dt">y =</span> latitude, <span class="dt">color =</span> plotvar), <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb89-9" data-line-number="9"><span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">mid=</span> <span class="st">&quot;white&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">aesthetics =</span> <span class="st">&#39;color&#39;</span>,</a>
<a class="sourceLine" id="cb89-10" data-line-number="10">                       <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dt">by =</span> <span class="dv">1</span>), <span class="dt">guide =</span> <span class="st">&#39;colorbar&#39;</span>, <span class="dt">name =</span> leglable) <span class="op">+</span></a>
<a class="sourceLine" id="cb89-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Longitude&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Latitude&quot;</span>, <span class="dt">title =</span> plottitle) </a></code></pre></div>
<p><img src="lec13_files/figure-html/mr15-1.png" width="2100" /></p>
<p>Get the Moran statistic for the residuals.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1"><span class="co"># Moran test</span></a>
<a class="sourceLine" id="cb90-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm1), <span class="dt">zero.policy=</span>T, </a>
<a class="sourceLine" id="cb90-3" data-line-number="3">     <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm1)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 2.4847, p-value = 0.006484
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.114991133      -0.008547009       0.002472130</code></pre>
<p>Note that this model is better behaved in the sense of not showing strange values for the standard errors of the regresssion coefficients, and the spatial autocorrelation, while still barely significant, is lower too. Many of the <em>t</em>-tests of the regression coefficients are not significant (meaning that the null hypothesis that the regression coefficient value is 0 can not be rejected). A model with a subset of (significant) predictors can be selected using “all/best possible subsets” regression.</p>
<p>Note that the condition number for this model is still relatively high, because, even though the predictor variables have been transformed, there is still a lot of correlation among them.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" data-line-number="1"><span class="kw">kappa</span>(tmeanjul_lm1)</a></code></pre></div>
<pre><code>## [1] 583.5609</code></pre>
</div>
<div id="all-possible-subsets-regression" class="section level2">
<h2><span class="header-section-number">5.5</span> All possible subsets regression</h2>
<p>The <code>regsubsets()</code> function in the <code>leaps</code> package uses a clever algorithm from the field of numerical analysis to examine a large (possibly all) set regressions with subsets of the predictors.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" data-line-number="1"><span class="co"># another model, all possible subsets regression</span></a>
<a class="sourceLine" id="cb94-2" data-line-number="2">tmeanjul_lm2 &lt;-<span class="st"> </span><span class="kw">regsubsets</span>(tmeanjul <span class="op">~</span><span class="st"> </span>Picea<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Abies<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Junip<span class="fl">.100</span></a>
<a class="sourceLine" id="cb94-3" data-line-number="3">    <span class="op">+</span><span class="st"> </span>Pinus<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Betula<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Frax<span class="fl">.15</span> <span class="op">+</span><span class="st"> </span>Querc<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Ulmus<span class="fl">.25</span></a>
<a class="sourceLine" id="cb94-4" data-line-number="4">    <span class="op">+</span><span class="st"> </span>Acer<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Juglans<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Carya<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Tsuga<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Fagus<span class="fl">.100</span></a>
<a class="sourceLine" id="cb94-5" data-line-number="5">    <span class="op">+</span><span class="st"> </span>Alnus<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Herbs<span class="fl">.25</span>, <span class="dt">data=</span>midwtf2)</a>
<a class="sourceLine" id="cb94-6" data-line-number="6"><span class="kw">summary</span>(tmeanjul_lm2)</a></code></pre></div>
<pre><code>## Subset selection object
## Call: regsubsets.formula(tmeanjul ~ Picea.50 + Abies.100 + Junip.100 + 
##     Pinus.100 + Betula.50 + Frax.15 + Querc.25 + Ulmus.25 + Acer.100 + 
##     Juglans.25 + Carya.25 + Tsuga.100 + Fagus.100 + Alnus.100 + 
##     Herbs.25, data = midwtf2)
## 15 Variables  (and intercept)
##            Forced in Forced out
## Picea.50       FALSE      FALSE
## Abies.100      FALSE      FALSE
## Junip.100      FALSE      FALSE
## Pinus.100      FALSE      FALSE
## Betula.50      FALSE      FALSE
## Frax.15        FALSE      FALSE
## Querc.25       FALSE      FALSE
## Ulmus.25       FALSE      FALSE
## Acer.100       FALSE      FALSE
## Juglans.25     FALSE      FALSE
## Carya.25       FALSE      FALSE
## Tsuga.100      FALSE      FALSE
## Fagus.100      FALSE      FALSE
## Alnus.100      FALSE      FALSE
## Herbs.25       FALSE      FALSE
## 1 subsets of each size up to 8
## Selection Algorithm: exhaustive
##          Picea.50 Abies.100 Junip.100 Pinus.100 Betula.50 Frax.15 Querc.25 Ulmus.25 Acer.100 Juglans.25
## 1  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot; &quot;       
## 2  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot; &quot;       
## 3  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot; &quot;       
## 4  ( 1 ) &quot;*&quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot; &quot;       
## 5  ( 1 ) &quot;*&quot;      &quot;*&quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot; &quot;       
## 6  ( 1 ) &quot;*&quot;      &quot;*&quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot; &quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot;*&quot;       
## 7  ( 1 ) &quot;*&quot;      &quot;*&quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot;*&quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot;*&quot;       
## 8  ( 1 ) &quot;*&quot;      &quot;*&quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;       &quot;*&quot;     &quot;*&quot;      &quot; &quot;      &quot; &quot;      &quot;*&quot;       
##          Carya.25 Tsuga.100 Fagus.100 Alnus.100 Herbs.25
## 1  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot; &quot;     
## 2  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot; &quot;     
## 3  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;     
## 4  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;     
## 5  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;     
## 6  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;     
## 7  ( 1 ) &quot; &quot;      &quot; &quot;       &quot; &quot;       &quot; &quot;       &quot;*&quot;     
## 8  ( 1 ) &quot; &quot;      &quot; &quot;       &quot;*&quot;       &quot; &quot;       &quot;*&quot;</code></pre>
<p>To get the diagnostic plots and statistics for one of the “best” models, that regression is simly rerun using the <code>lm()</code> function.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" data-line-number="1"><span class="co"># rerun one of the best-subsets regressions</span></a>
<a class="sourceLine" id="cb96-2" data-line-number="2">tmeanjul_lm3 &lt;-<span class="st"> </span><span class="kw">lm</span>(tmeanjul <span class="op">~</span><span class="st"> </span>Picea<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Abies<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Betula<span class="fl">.50</span> <span class="op">+</span><span class="st"> </span>Fraxinus</a>
<a class="sourceLine" id="cb96-3" data-line-number="3">     <span class="op">+</span><span class="st"> </span>Querc<span class="fl">.25</span> <span class="op">+</span><span class="st"> </span>Fagus<span class="fl">.100</span> <span class="op">+</span><span class="st"> </span>Herbs<span class="fl">.25</span>)</a>
<a class="sourceLine" id="cb96-4" data-line-number="4"></a>
<a class="sourceLine" id="cb96-5" data-line-number="5"><span class="kw">summary</span>(tmeanjul_lm3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = tmeanjul ~ Picea.50 + Abies.100 + Betula.50 + Fraxinus + 
##     Querc.25 + Fagus.100 + Herbs.25)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.39534 -0.48327 -0.03144  0.44866  2.04798 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 18.65800    0.75739  24.634  &lt; 2e-16 ***
## Picea.50    -0.40341    0.16651  -2.423  0.01695 *  
## Abies.100   -0.31768    0.15364  -2.068  0.04089 *  
## Betula.50   -0.23057    0.05388  -4.279 3.88e-05 ***
## Fraxinus     0.10115    0.05271   1.919  0.05743 .  
## Querc.25     1.09737    0.21597   5.081 1.45e-06 ***
## Fagus.100   -0.05251    0.03093  -1.698  0.09224 .  
## Herbs.25     0.65599    0.21910   2.994  0.00337 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7173 on 116 degrees of freedom
## Multiple R-squared:  0.8149, Adjusted R-squared:  0.8037 
## F-statistic: 72.96 on 7 and 116 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb98-2" data-line-number="2"><span class="kw">plot</span>(tmeanjul_lm1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/mr19-1.png" width="2100" /></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" data-line-number="1"><span class="co"># ggplot2 map of residuals</span></a>
<a class="sourceLine" id="cb100-2" data-line-number="2">plotvar &lt;-<span class="st"> </span><span class="kw">residuals</span>(tmeanjul_lm3)</a>
<a class="sourceLine" id="cb100-3" data-line-number="3">plotvar &lt;-<span class="st"> </span>plotvar<span class="op">-</span><span class="kw">mean</span>(plotvar)</a>
<a class="sourceLine" id="cb100-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;All-possible subsets model residuals (C)&quot;</span></a>
<a class="sourceLine" id="cb100-5" data-line-number="5">leglable &lt;-<span class="st"> &quot;residuals tmeanjul_lm3&quot;</span></a>
<a class="sourceLine" id="cb100-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb100-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> midwotl_sf, <span class="dt">fill=</span><span class="st">&quot;grey70&quot;</span>, <span class="dt">color=</span><span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb100-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> midwtf2, <span class="kw">aes</span>(<span class="dt">x =</span> longitud, <span class="dt">y =</span> latitude, <span class="dt">color =</span> plotvar), <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb100-9" data-line-number="9"><span class="st">  </span><span class="kw">scale_fill_gradient2</span>(<span class="dt">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">mid=</span> <span class="st">&quot;white&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">aesthetics =</span> <span class="st">&#39;color&#39;</span>,</a>
<a class="sourceLine" id="cb100-10" data-line-number="10">                       <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dt">by =</span> <span class="dv">1</span>), <span class="dt">guide =</span> <span class="st">&#39;colorbar&#39;</span>, <span class="dt">name =</span> leglable) <span class="op">+</span></a>
<a class="sourceLine" id="cb100-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Longitude&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Latitude&quot;</span>, <span class="dt">title =</span> plottitle) </a></code></pre></div>
<p><img src="lec13_files/figure-html/mr20-1.png" width="2100" /></p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" data-line-number="1"><span class="co"># Moran test</span></a>
<a class="sourceLine" id="cb101-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm3), <span class="dt">zero.policy=</span>T,</a>
<a class="sourceLine" id="cb101-3" data-line-number="3">    <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm3)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 1.8408, p-value = 0.03283
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.082845436      -0.008547009       0.002464961</code></pre>
<p>The condition number is now acceptably low:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1"><span class="kw">kappa</span>(tmeanjul_lm3)</a></code></pre></div>
<pre><code>## [1] 49.40867</code></pre>
<p>The progress of the analysis can be gauged by comparing the individual Moran statistics, which should get smaller as the model gets more refined. The Moran statistic for the data is 12.08, and this could be thought of as a “totally naive” model, where the response variable is expressed as a function of just its mean value. The naive model with all untransformed predictors does achieve a lower Moran statistic (2.197) indicating that some of the pattern in the response has indeed been accounted for by the predictors, but there are other issues with this model. The second regression including transformed predictors has a Moran statistic of 2.480, but this model too has some issues, in particular, it is “overfit”. The final model, the result of the best-possible-subsets regression has the lowest Moran statistics too, 1.834.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1"><span class="co"># compare Moran tests</span></a>
<a class="sourceLine" id="cb105-2" data-line-number="2"><span class="co"># dependent variable (tmeanjul)</span></a>
<a class="sourceLine" id="cb105-3" data-line-number="3"><span class="kw">moran.test</span>(tmeanjul, <span class="dt">zero.policy=</span>T, </a>
<a class="sourceLine" id="cb105-4" data-line-number="4">     <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  tmeanjul  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 12.081, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.592512863      -0.008547009       0.002475262</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1"><span class="co"># lm0 (naive model) no transformation, all predictors included</span></a>
<a class="sourceLine" id="cb107-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm0), <span class="dt">zero.policy=</span>T,</a>
<a class="sourceLine" id="cb107-3" data-line-number="3">    <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm0)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 2.1997, p-value = 0.01392
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.100919178      -0.008547009       0.002476578</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="co"># lm1 transformed predictors, all predictors included</span></a>
<a class="sourceLine" id="cb109-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm1), <span class="dt">zero.policy=</span>T,</a>
<a class="sourceLine" id="cb109-3" data-line-number="3">    <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm1)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 2.4847, p-value = 0.006484
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.114991133      -0.008547009       0.002472130</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" data-line-number="1"><span class="co"># lm3 transformed predictors, best subset model</span></a>
<a class="sourceLine" id="cb111-2" data-line-number="2"><span class="kw">moran.test</span>(<span class="kw">residuals</span>(tmeanjul_lm3), <span class="dt">zero.policy=</span>T,</a>
<a class="sourceLine" id="cb111-3" data-line-number="3">    <span class="kw">nb2listw</span>(midwtf2_neighbors_dist, <span class="dt">zero.policy=</span>T, <span class="dt">style=</span><span class="st">&quot;W&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  residuals(tmeanjul_lm3)  
## weights: nb2listw(midwtf2_neighbors_dist, zero.policy = T, style = &quot;W&quot;)  n reduced by no-neighbour observations
##   
## 
## Moran I statistic standard deviate = 1.8408, p-value = 0.03283
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.082845436      -0.008547009       0.002464961</code></pre>
<p><a href="lec13.html">[Back to top]</a></p>
</div>
</div>
<div id="another-example-dummy-variable-regression" class="section level1">
<h1><span class="header-section-number">6</span> Another example – dummy-variable regression</h1>
<p>Sometimes a data set exists in which fitting different relationships for subsets of the observations are in order. This situation is exemplified by the Scandinavian EU preference data. The technique knows as <em>dummy-variable</em> regression allows the simulataneous calculation of separate regression lines for subsets of the data, or in the example here, for the individual countries. The regression lines can vary in either their slopes or intercepts, or both.</p>
<p>Here are the shapefile components, which include the data: <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/scand.dbf">[.dbf]</a> <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/scand.shx">[.shx]</a> <a href="https://pjbartlein.github.io/GeogDataAnalysis/data/shp/scand.shp">[.shp]</a></p>
<p>Load some packages, and attach the data frame:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" data-line-number="1"><span class="kw">library</span>(sf)</a>
<a class="sourceLine" id="cb113-2" data-line-number="2"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb113-3" data-line-number="3"><span class="kw">library</span>(RColorBrewer)</a></code></pre></div>
<div id="look-at-the-data" class="section level2">
<h2><span class="header-section-number">6.1</span> Look at the data</h2>
<p>First, get a reference map of the commune/county/district names. Read a shapefile of Scandanavian communes.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" data-line-number="1"><span class="co"># read a Scandinamvian province/county shape file</span></a>
<a class="sourceLine" id="cb114-2" data-line-number="2">shapefile &lt;-<span class="st"> &quot;/Users/bartlein/Documents/geog495/data/shp/scand_prov.shp&quot;</span></a>
<a class="sourceLine" id="cb114-3" data-line-number="3">scand_prov_sf &lt;-<span class="st"> </span><span class="kw">st_read</span>(shapefile)</a>
<a class="sourceLine" id="cb114-4" data-line-number="4">scand_prov_sf</a>
<a class="sourceLine" id="cb114-5" data-line-number="5"><span class="kw">plot</span>(<span class="kw">st_geometry</span>(scand_prov_sf), <span class="dt">axes =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Get the centroids of the individual districts for locating labels later:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" data-line-number="1"><span class="co"># get coordinates of district centroids</span></a>
<a class="sourceLine" id="cb115-2" data-line-number="2">scand_prov_pts &lt;-<span class="st"> </span>(<span class="kw">st_centroid</span>(scand_prov_sf))</a></code></pre></div>
<pre><code>## Warning in st_centroid.sf(scand_prov_sf): st_centroid assumes attributes are constant over geometries of
## x</code></pre>
<pre><code>## Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon = of_largest_polygon): st_centroid does not
## give correct centroids for longitude/latitude data</code></pre>
<p>Ignore the warning, which alerts us to the fact that latitude and longitude are not isotropic, and so we really should be calculating centroids only with projected data.</p>
<p>Plot the District (commune) names:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" data-line-number="1"><span class="co"># ggplot2 map of District names</span></a>
<a class="sourceLine" id="cb118-2" data-line-number="2"><span class="kw">ggplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb118-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> scand_prov_sf, <span class="dt">fill=</span><span class="ot">NA</span>, <span class="dt">color=</span><span class="st">&quot;gray&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb118-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_sf_text</span>(<span class="dt">data =</span> scand_prov_pts, <span class="kw">aes</span>(<span class="dt">geometry=</span>geometry, <span class="dt">label=</span><span class="kw">as.character</span>(District)), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb118-5" data-line-number="5"><span class="st">  </span><span class="kw">coord_sf</span>(<span class="dt">xlim=</span><span class="kw">c</span>(<span class="fl">2.5</span>,<span class="fl">32.5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb118-6" data-line-number="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Longitude&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Latitude&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb118-7" data-line-number="7"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not give correct results for
## longitude/latitude data</code></pre>
<p><img src="lec13_files/figure-html/plot%20names-1.png" width="2100" /></p>
<p>Next, extact the variable values from the shape file, and plot the yes votes. (The data are the same as those in <code>scanvote_csv</code>, but are extracted from the shapefile here to make sure that the individual values are in the same order as the polygons in the shapefile.)</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" data-line-number="1"><span class="co"># get variable values from .dbf attributes</span></a>
<a class="sourceLine" id="cb120-2" data-line-number="2">Y &lt;-<span class="st"> </span>scand_prov_sf<span class="op">$</span>Yes</a>
<a class="sourceLine" id="cb120-3" data-line-number="3">X &lt;-<span class="st"> </span>scand_prov_sf<span class="op">$</span>Pop</a>
<a class="sourceLine" id="cb120-4" data-line-number="4">Country &lt;-<span class="st"> </span>scand_prov_sf<span class="op">$</span>Country</a></code></pre></div>
<p>Plot the “Yes” vote:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" data-line-number="1"><span class="co"># plot Yes votes -- setup</span></a>
<a class="sourceLine" id="cb121-2" data-line-number="2">pal &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;PuOr&quot;</span>) </a>
<a class="sourceLine" id="cb121-3" data-line-number="3"><span class="kw">ggplot</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb121-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> scand_prov_sf, <span class="kw">aes</span>(<span class="dt">fill =</span> Yes)) <span class="op">+</span></a>
<a class="sourceLine" id="cb121-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_sf_text</span>(<span class="dt">data =</span> scand_prov_pts, <span class="kw">aes</span>(<span class="dt">geometry=</span>geometry, <span class="dt">label=</span><span class="kw">as.character</span>(Yes)), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb121-6" data-line-number="6"><span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colors =</span> pal) <span class="op">+</span></a>
<a class="sourceLine" id="cb121-7" data-line-number="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Yes Vote (%)&quot;</span>, <span class="dt">x=</span><span class="st">&quot;Longitude&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Latitude&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not give correct results for
## longitude/latitude data</code></pre>
<p><img src="lec13_files/figure-html/unnamed-chunk-5-1.png" width="2100" /></p>
<p>Here’s a standard scatter plot of the data, with the points labeled by Country.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" data-line-number="1"><span class="co"># scatter plot with Country labels</span></a>
<a class="sourceLine" id="cb123-2" data-line-number="2"><span class="kw">plot</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X), <span class="dt">type=</span><span class="st">&quot;n&quot;</span>)</a>
<a class="sourceLine" id="cb123-3" data-line-number="3"><span class="kw">text</span>(<span class="kw">log10</span>(X),Y, <span class="dt">labels=</span>Country, <span class="dt">cex=</span><span class="fl">0.8</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum05-1.png" width="2100" /></p>
</div>
<div id="first-regression-all-data" class="section level2">
<h2><span class="header-section-number">6.2</span> First regression, all data</h2>
<p>The regression model for all data, considered without respect to individual country is as follows:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" data-line-number="1"><span class="co"># linear model, Yes ~ log10(Pop)</span></a>
<a class="sourceLine" id="cb124-2" data-line-number="2">vote_lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X))</a>
<a class="sourceLine" id="cb124-3" data-line-number="3"><span class="kw">summary</span>(vote_lm1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ log10(X))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.8422  -3.9810  -0.3129   2.9602  15.3838 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   28.815      2.244  12.842  &lt; 2e-16 ***
## log10(X)      14.673      1.593   9.211 1.37e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.261 on 53 degrees of freedom
## Multiple R-squared:  0.6155, Adjusted R-squared:  0.6083 
## F-statistic: 84.85 on 1 and 53 DF,  p-value: 1.372e-12</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" data-line-number="1">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb126-2" data-line-number="2"><span class="kw">plot</span>(vote_lm1, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum06-1.png" width="2100" /></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<p>The initial regression has several issues: There is a distinct arch in the residual scatter plot, the Normal QQ plot indicates there are several outliers, and the Cook’s distance and leverage plots indicate the presence of several overly influential observations. Further examination of the results is warrented.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" data-line-number="1"><span class="co"># examine the regression equation</span></a>
<a class="sourceLine" id="cb128-2" data-line-number="2"><span class="kw">plot</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X), <span class="dt">type=</span><span class="st">&quot;n&quot;</span>)</a>
<a class="sourceLine" id="cb128-3" data-line-number="3"><span class="kw">text</span>(<span class="kw">log10</span>(X),Y, <span class="dt">labels=</span>Country)</a>
<a class="sourceLine" id="cb128-4" data-line-number="4"><span class="kw">abline</span>(vote_lm1)</a>
<a class="sourceLine" id="cb128-5" data-line-number="5"><span class="kw">segments</span>(<span class="kw">log10</span>(X), <span class="kw">fitted</span>(vote_lm1), <span class="kw">log10</span>(X), Y)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum07-1.png" width="2100" /></p>
<p>Examination of this plot suggests that positive deviations are often contributed by communes in Finland, and negative deviations by communes in Norway. This suggests that Norwegian communes are less likely to have voted Yes, and Finnish communes more likely to have voted yes than Scandinavian communes as a group. This idea is reinforced by looking at the prediction and confidence intervals for the regression.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" data-line-number="1"><span class="co"># confidence intervals</span></a>
<a class="sourceLine" id="cb129-2" data-line-number="2">pred_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">X=</span><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">1151</span>,<span class="dt">by=</span><span class="dv">50</span>))</a>
<a class="sourceLine" id="cb129-3" data-line-number="3">pred_int &lt;-<span class="st"> </span><span class="kw">predict</span>(vote_lm1, <span class="dt">int=</span><span class="st">&quot;p&quot;</span>, <span class="dt">newdata=</span>pred_data)</a>
<a class="sourceLine" id="cb129-4" data-line-number="4">conf_int &lt;-<span class="st"> </span><span class="kw">predict</span>(vote_lm1, <span class="dt">int=</span><span class="st">&quot;c&quot;</span>, <span class="dt">newdata=</span>pred_data)</a>
<a class="sourceLine" id="cb129-5" data-line-number="5"></a>
<a class="sourceLine" id="cb129-6" data-line-number="6"><span class="kw">plot</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X), <span class="dt">ylim=</span><span class="kw">range</span>(Y, pred_int, <span class="dt">na.rm=</span>T), <span class="dt">type=</span><span class="st">&quot;n&quot;</span>)</a>
<a class="sourceLine" id="cb129-7" data-line-number="7"><span class="kw">text</span>(<span class="kw">log10</span>(X),Y, <span class="dt">labels=</span>Country, <span class="dt">cex=</span><span class="fl">0.7</span>)</a>
<a class="sourceLine" id="cb129-8" data-line-number="8">pred_X &lt;-<span class="st"> </span><span class="kw">log10</span>(pred_data<span class="op">$</span>X)</a>
<a class="sourceLine" id="cb129-9" data-line-number="9"><span class="kw">matlines</span>(pred_X, pred_int, <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">col=</span><span class="st">&quot;black&quot;</span>)</a>
<a class="sourceLine" id="cb129-10" data-line-number="10"><span class="kw">matlines</span>(pred_X, conf_int, <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum08-1.png" width="2100" /></p>
<p>Mapping the residuals suggests the same thing–there is an obvious spatial pattern in the sign of the residuals (so obvious, that it’s not really necessary to calculate a Moran statistic).</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" data-line-number="1"><span class="co"># map the residuals</span></a>
<a class="sourceLine" id="cb130-2" data-line-number="2">pal &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;PuOr&quot;</span>) </a>
<a class="sourceLine" id="cb130-3" data-line-number="3">plotlab &lt;-<span class="st"> </span><span class="kw">as.character</span>(<span class="kw">round</span>(vote_lm1<span class="op">$</span>residuals, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb130-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Residuals from lm1&quot;</span></a>
<a class="sourceLine" id="cb130-5" data-line-number="5"><span class="kw">ggplot</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb130-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> scand_prov_sf, <span class="kw">aes</span>(<span class="dt">fill =</span> vote_lm1<span class="op">$</span>residuals)) <span class="op">+</span></a>
<a class="sourceLine" id="cb130-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf_text</span>(<span class="dt">data =</span> scand_prov_pts, <span class="kw">aes</span>(<span class="dt">geometry=</span>geometry, <span class="dt">label=</span>plotlab), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb130-8" data-line-number="8"><span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colors =</span> pal, <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>, <span class="dt">by =</span> <span class="dv">5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb130-9" data-line-number="9"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> plottitle, <span class="dt">x=</span><span class="st">&quot;Longitude&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Latitude&quot;</span>) </a></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not give correct results for
## longitude/latitude data</code></pre>
<p><img src="lec13_files/figure-html/dum09-1.png" width="2100" /></p>
<p>Boxplots of the response variable (<code>Y</code>) and the residuals by country also suggest the same thing.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" data-line-number="1">opar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb132-2" data-line-number="2"><span class="co"># country-effect</span></a>
<a class="sourceLine" id="cb132-3" data-line-number="3"><span class="kw">boxplot</span>(Y <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylab=</span><span class="st">&quot;Yes&quot;</span>)</a>
<a class="sourceLine" id="cb132-4" data-line-number="4"></a>
<a class="sourceLine" id="cb132-5" data-line-number="5"><span class="co"># residual grouped boxplot</span></a>
<a class="sourceLine" id="cb132-6" data-line-number="6"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm1) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb132-7" data-line-number="7">par &lt;-<span class="st"> </span>opar</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum10-1.png" width="2100" /></p>
</div>
<div id="dummy-variable-regression-with-country-as-a-predictor" class="section level2">
<h2><span class="header-section-number">6.3</span> Dummy variable regression, with Country as a predictor</h2>
<p>A dummy-variable regression can be run by including <code>Country</code> as a predictor. The formula <code>Y ~ log10(X)+Country</code> specifies a regression in which separate intercept values are calculated for each country. In essence, two new variables are generated, each binary (0 or 1), one for Sweden and the other for Norway. The intercepts that are estimated work as follows: The “plain” intercept applies to the country left out (Finland), while the intercept for Sweden is that value plus the coefficient estimated for Sweden, and likewise for Norway.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" data-line-number="1"><span class="co"># Scandinavian EU Preference Vote -- dummy variable regression</span></a>
<a class="sourceLine" id="cb133-2" data-line-number="2"><span class="co"># model with a factor as predictor</span></a>
<a class="sourceLine" id="cb133-3" data-line-number="3">vote_lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X)<span class="op">+</span>Country)</a>
<a class="sourceLine" id="cb133-4" data-line-number="4"><span class="kw">summary</span>(vote_lm2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ log10(X) + Country)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.0158 -3.7002 -0.3915  2.8713 16.3456 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   34.434      2.332  14.769  &lt; 2e-16 ***
## log10(X)      14.880      1.400  10.629 1.55e-14 ***
## CountryN      -8.609      2.004  -4.296 7.82e-05 ***
## CountryS      -6.679      1.936  -3.451  0.00113 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.435 on 51 degrees of freedom
## Multiple R-squared:  0.7212, Adjusted R-squared:  0.7048 
## F-statistic: 43.98 on 3 and 51 DF,  p-value: 3.537e-14</code></pre>
<p>The different regression lines can be displayed as follows:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" data-line-number="1"><span class="co"># display the fitted lines</span></a>
<a class="sourceLine" id="cb135-2" data-line-number="2"><span class="kw">plot</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X))</a>
<a class="sourceLine" id="cb135-3" data-line-number="3"><span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N&quot;</span>,<span class="st">&quot;F&quot;</span>,<span class="st">&quot;S&quot;</span>), <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">cex=</span><span class="dv">1</span>, <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;purple&quot;</span>))</a>
<a class="sourceLine" id="cb135-4" data-line-number="4"></a>
<a class="sourceLine" id="cb135-5" data-line-number="5"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;N&quot;</span>],<span class="kw">fitted</span>(vote_lm2)[Country<span class="op">==</span><span class="st">&quot;N&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb135-6" data-line-number="6"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;F&quot;</span>],<span class="kw">fitted</span>(vote_lm2)[Country<span class="op">==</span><span class="st">&quot;F&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb135-7" data-line-number="7"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;S&quot;</span>],<span class="kw">fitted</span>(vote_lm2)[Country<span class="op">==</span><span class="st">&quot;S&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum12-1.png" width="2100" /></p>
<p>Notice that Finland has the highest intercept (34.434), while that for Sweden is lower (34.434 - 6.679), and that for Norway is lower still (34.434 - 8.609).</p>
<p>Examine the model</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" data-line-number="1"><span class="co"># examine the model</span></a>
<a class="sourceLine" id="cb136-2" data-line-number="2">oldpar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb136-3" data-line-number="3"><span class="kw">plot</span>(vote_lm2, <span class="dt">which=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum13-1.png" width="2100" /></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" data-line-number="1"><span class="kw">par</span>(oldpar)</a></code></pre></div>
<p>The obvious arch in the residual scatter plot is much less obvious, as is the departure from normality of the residuals. There are still a few overly influential points, but their influence is reduced as well.</p>
<p>Map the residuals:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" data-line-number="1"><span class="co"># map residuals</span></a>
<a class="sourceLine" id="cb138-2" data-line-number="2">pal &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;PuOr&quot;</span>) </a>
<a class="sourceLine" id="cb138-3" data-line-number="3">plotlab &lt;-<span class="st"> </span><span class="kw">as.character</span>(<span class="kw">round</span>(vote_lm2<span class="op">$</span>residuals, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb138-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Residuals from lm2&quot;</span></a>
<a class="sourceLine" id="cb138-5" data-line-number="5"><span class="kw">ggplot</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb138-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> scand_prov_sf, <span class="kw">aes</span>(<span class="dt">fill =</span> vote_lm2<span class="op">$</span>residuals)) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf_text</span>(<span class="dt">data =</span> scand_prov_pts, <span class="kw">aes</span>(<span class="dt">geometry=</span>geometry, <span class="dt">label=</span>plotlab), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-8" data-line-number="8"><span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colors =</span> pal, <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>, <span class="dt">by =</span> <span class="dv">5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-9" data-line-number="9"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> plottitle, <span class="dt">x=</span><span class="st">&quot;Longitude&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Latitude&quot;</span>) </a></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not give correct results for
## longitude/latitude data</code></pre>
<p><img src="lec13_files/figure-html/dum14-1.png" width="2100" /></p>
<p>The obvious patterns in the residuals from the first regression are also much reduced.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" data-line-number="1">opar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb140-2" data-line-number="2"><span class="co"># country-effect</span></a>
<a class="sourceLine" id="cb140-3" data-line-number="3"><span class="kw">boxplot</span>(Y <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylab=</span><span class="st">&quot;Yes&quot;</span>)</a>
<a class="sourceLine" id="cb140-4" data-line-number="4"></a>
<a class="sourceLine" id="cb140-5" data-line-number="5"><span class="co"># residual grouped boxplot</span></a>
<a class="sourceLine" id="cb140-6" data-line-number="6"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm1) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb140-7" data-line-number="7"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm2) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb140-8" data-line-number="8">par &lt;-<span class="st"> </span>opar</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum19-1.png" width="2100" /></p>
<p>It also the case that the obvious differences in the location (i.e. the medians), and scale (the interquartile range) of the residuals (as illustrated by the boxplots) in the first regression model is reduced, bringing the residuals more in line with the assumption that they are independent and identically distributed.</p>
</div>
<div id="dummy-variable-regression-with-both-slope-and-intercept-varying-by-country" class="section level2">
<h2><span class="header-section-number">6.4</span> Dummy-variable regression with both slope and intercept varying by Country</h2>
<p>A second dummy variable regression, where both the intercept and slope vary can be specified using the model formula `Y ~ log10(X)*Country’.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" data-line-number="1">vote_lm3 &lt;-<span class="st"> </span><span class="kw">lm</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X)<span class="op">*</span>Country)</a>
<a class="sourceLine" id="cb141-2" data-line-number="2"><span class="kw">summary</span>(vote_lm3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ log10(X) * Country)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.7389 -3.6772 -0.6104  3.0088 15.2611 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        34.1513     5.0934   6.705  1.9e-08 ***
## log10(X)           15.1096     3.9269   3.848 0.000345 ***
## CountryN           -9.5210     5.8462  -1.629 0.109817    
## CountryS           -4.7507     6.0771  -0.782 0.438131    
## log10(X):CountryN   0.7397     4.4484   0.166 0.868612    
## log10(X):CountryS  -1.4059     4.5151  -0.311 0.756828    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.517 on 49 degrees of freedom
## Multiple R-squared:  0.724,  Adjusted R-squared:  0.6959 
## F-statistic: 25.71 on 5 and 49 DF,  p-value: 1.24e-12</code></pre>
<p>None of the <em>t</em>-tests of the significance of the dummy-variable terms (intercepts and slopes) are significant, and the adjusted <em>R<sup>2</sup></em> value is lower, and so this model is likely “overfitted”. Nevertheless, it’s useful to look at how both the intercepts and slopes can be made to vary amoung countries.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" data-line-number="1"><span class="co"># display the fitted lines</span></a>
<a class="sourceLine" id="cb143-2" data-line-number="2"><span class="kw">plot</span>(Y <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(X))</a>
<a class="sourceLine" id="cb143-3" data-line-number="3"><span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N&quot;</span>,<span class="st">&quot;F&quot;</span>,<span class="st">&quot;S&quot;</span>), <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">cex=</span><span class="dv">1</span>, <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;purple&quot;</span>))</a>
<a class="sourceLine" id="cb143-4" data-line-number="4"></a>
<a class="sourceLine" id="cb143-5" data-line-number="5"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;N&quot;</span>],<span class="kw">fitted</span>(vote_lm3)[Country<span class="op">==</span><span class="st">&quot;N&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb143-6" data-line-number="6"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;F&quot;</span>],<span class="kw">fitted</span>(vote_lm3)[Country<span class="op">==</span><span class="st">&quot;F&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb143-7" data-line-number="7"><span class="kw">lines</span>(<span class="kw">log10</span>(X)[Country<span class="op">==</span><span class="st">&quot;S&quot;</span>],<span class="kw">fitted</span>(vote_lm3)[Country<span class="op">==</span><span class="st">&quot;S&quot;</span>], <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum16-1.png" width="2100" /> Map the residuals from the third model.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1"><span class="co"># map residuals</span></a>
<a class="sourceLine" id="cb144-2" data-line-number="2">pal &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;PuOr&quot;</span>) </a>
<a class="sourceLine" id="cb144-3" data-line-number="3">plotlab &lt;-<span class="st"> </span><span class="kw">as.character</span>(<span class="kw">round</span>(vote_lm3<span class="op">$</span>residuals, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb144-4" data-line-number="4">plottitle &lt;-<span class="st"> &quot;Residuals from lm3&quot;</span></a>
<a class="sourceLine" id="cb144-5" data-line-number="5"><span class="kw">ggplot</span>()  <span class="op">+</span></a>
<a class="sourceLine" id="cb144-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> scand_prov_sf, <span class="kw">aes</span>(<span class="dt">fill =</span> vote_lm3<span class="op">$</span>residuals)) <span class="op">+</span></a>
<a class="sourceLine" id="cb144-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_sf_text</span>(<span class="dt">data =</span> scand_prov_pts, <span class="kw">aes</span>(<span class="dt">geometry=</span>geometry, <span class="dt">label=</span>plotlab), <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb144-8" data-line-number="8"><span class="st">  </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colors =</span> pal, <span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>, <span class="dt">by =</span> <span class="dv">5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb144-9" data-line-number="9"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> plottitle, <span class="dt">x=</span><span class="st">&quot;Longitude&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Latitude&quot;</span>) </a></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not give correct results for
## longitude/latitude data</code></pre>
<p><img src="lec13_files/figure-html/dum17-1.png" width="2100" /></p>
<p>Look at the country effect on the residuals from the third model.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" data-line-number="1"><span class="co"># country-effect</span></a>
<a class="sourceLine" id="cb146-2" data-line-number="2">opar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb146-3" data-line-number="3"><span class="kw">boxplot</span>(Y <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylab=</span><span class="st">&quot;Yes&quot;</span>)</a>
<a class="sourceLine" id="cb146-4" data-line-number="4"></a>
<a class="sourceLine" id="cb146-5" data-line-number="5"><span class="co"># residual grouped boxplot</span></a>
<a class="sourceLine" id="cb146-6" data-line-number="6"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm1) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb146-7" data-line-number="7"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm2) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb146-8" data-line-number="8"><span class="kw">plot</span>(<span class="kw">residuals</span>(vote_lm3) <span class="op">~</span><span class="st"> </span>Country, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">15</span>,<span class="dv">15</span>))</a></code></pre></div>
<p><img src="lec13_files/figure-html/dum18-1.png" width="2100" /></p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" data-line-number="1">par &lt;-<span class="st"> </span>opar</a></code></pre></div>
<p>There is little difference between the third model (in which the slope and the intercept vary amoung countries) and the second, and so the “principle of parsimony” would indicate that the second model should be preferred.</p>
<p><a href="lec13.html">[Back to top]</a></p>
</div>
</div>
<div id="readings" class="section level1">
<h1><span class="header-section-number">7</span> Readings</h1>
<ul>
<li>Kuhnert &amp; Venebles (<em>An Introduction…</em>): p. 109-120<br />
</li>
<li>Maindonald (<em>Using R…</em>): ch. 5</li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
